exp/docgen/settings.sample.php
exp/docgen/www/index.php
exp/docgen/www/script.js
exp/docgen/www/search.php
exp/docgen/www/style.css
exp/docgen/www/template/404.php
exp/docgen/www/template/class.php
exp/docgen/www/template/constants.php
exp/docgen/www/template/enum.php
exp/docgen/www/template/footer.php
exp/docgen/www/template/function.php
exp/docgen/www/template/header.php
exp/docgen/www/template/include.php
exp/docgen/www/template/main.php
exp/docgen/www/template/property.php
exp/docgen/www/template/raw.php
exp/docgen/www/template/render.php
exp/docgen/www/template/sidebar.php
exp/docgen/www/template/type.php
exp/docgen/www/template/type_helpers.php

This PR replaces crappy search with a proper one that filters the sidebar.
For improved performance, every `name` column should have an index added.
Other changes:
- Added a check to see if include exists before trying to find objects in it and renders 404 page if not found
- Breadcrumb improvements so that it actually says where you are now
- Added a panel saying there are no types/functions if include file exists but there is nothing to display
- Added a label with return type in return value section
- Made custom types clickable
- Added some poor type highlighting in syntax display
- A bunch of minor style related fixes

docgen updates

---

exp/docgen/www/.htaccess
exp/docgen/www/index.php
exp/docgen/www/script.js
exp/docgen/www/style.css
exp/docgen/www/template/404.php
exp/docgen/www/template/header.php
exp/docgen/www/template/main.php
exp/docgen/www/template/sidebar.php

Changes:
- Removes hacky rewrite fix I've added in previous PR
- Makes sidebar toggleable on smaller screens
- Nicer 404 page

Docgen update 2

---

vm/opcodes.cpp
vm/opcodes.h
vm/x86/jit_x86.cpp

Fixup the debug spew for recent layout changes.

Fix printing JIT opcodes with JIT_SPEW defined

---

vm/x86/jit_x86.cpp

Same fix as #26, but reorders the throw_timeout_ block.

Fix unbound return_reported_error_ label

---

compiler/sc3.cpp

Initially filed from: https://bugs.alliedmods.net/show_bug.cgi?id=6399
This horrible bug is that `value::ident` does not necessarily reflect lvalue-state. Unary operators `!`, `~`, and `-` all return false to indicate an rvalue, but do not change the value type to `iEXPRESSION`. I can't imagine a reason for this, so it just seems like a bug.

Fix some unary operators not correctly reflecting lvalue state. (bug 6399)

---

compiler/sc.h
compiler/sc1.cpp
compiler/sc2.cpp
compiler/scvars.cpp

Most of this is removing internal VM toggles that either don't work or shouldn't work. The other big change is removing reports/documentation, since the v2 compiler can do a much better job of this anyway.

Remove a bunch of unsupported junk.

---

vm/AMBuilder
vm/base-context.cpp
vm/base-context.h
vm/plugin-context.cpp
vm/plugin-context.h

This just makes it easier to have multiple derivations of IPluginContext.

Factor API access and generic functions out of PluginContext.

---

AMBuildScript

Reverts alliedmodders/sourcepawn#43

Revert "Fixed AMBuildScript for build option"

---

compiler/sc2.cpp

Code taken from
https://github.com/compuphase/pawn/blob/6de1822ac1625451bf151159bb0178c09f087bea/compiler/sc2.c#L519-530

Fix stripcom (bug 6424)

---

exp/compiler/source-manager.cpp
exp/compiler/source-manager.h
vm/file-utils.cpp
vm/file-utils.h
vm/plugin-runtime.cpp
vm/plugin-runtime.h
vm/scripted-invoker.cpp
vm/scripted-invoker.h
vm/smx-v1-image.cpp
vm/watchdog_timer.cpp

AutoPtr<T> doesn't support assignment from compatible AutoPtr<U>&& yet. Too lazy to fix that now, so the cases that needed it use assign() here.

Update to the latest AMTL.

---

vm/x86/assembler-x86.h

Add more x86 assembly instructions to MacroAssembler

---

AMBuildScript
compiler/AMBuilder
compiler/sc1.cpp
compiler/sc2.cpp
compiler/tests/runtests.py
tests/runtests.py
vm/AMBuilder
vm/plugin-context.cpp
vm/shell.cpp

```
source ~/emsdk_portable/emsdk_env.sh
CC=emcc CXX=emcc python3 ../configure.py --build=spcomp,vm --enable-optimize
ambuild
```

Support building spcomp and spshell with Emscripten

---

tests/basic/early-return.out
tests/basic/early-return.sp
vm/interpreter.cpp
vm/interpreter.h

@dvander still not 100% sure this is correct, but it seems to work and be sane, figured I'd give it a shot.

Stop executing opcodes after hitting a RETN (Fix #115)

---

compiler/sc1.cpp

Fixes `Assertion failed: strtol(ld->name,NULL,16)==count % dim[numdim-2]` in `fail-invalid-array-3d`.

Abort array parsing when encountering an error

---

compiler/sc3.cpp
compiler/sc5-in.scp
compiler/sctracker.cpp
compiler/sctracker.h
compiler/tests/fail-call-ctor-as-static.sp
compiler/tests/fail-call-ctor-as-static.txt

See: https://forums.alliedmods.net/showthread.php?t=297004

Fix assert and bad error messaging when using constructors as static methods.

---

compiler/sc3.cpp

Not sure if this is an acceptable solution to this issue, but I have tested it and it does work. Let me know.

Fix char literal tag mismatch (issue #136)

---

compiler/sc6.cpp

1. Extract a helper for desymbolizing function names, and forbid labels here.
2. Add a helper for writing to the buffer, to do away with null checks and hardcoded opcode sizes.

Various cleanups to the assembly process.

---

.appveyor/build.bat
.appveyor/setup_environment.bat
tests/runtests.py

P-M pointed out it seemed like AppVeyor wasn't doing... much of anything.  Upon investigation, AppVeyor wasn't doing much of anything.  Also turns out the newer test script stuff was broken on Windows anyway and was only checking for the first error line of failure tests (and was even doing _that_ improperly.)

Fix AppVeyor and tests.

---

.travis.yml

It's currently timing out on Travis. Disabling until we can figure out why.

Disable Emscripten CI

---

exp/compiler/types.cpp

Fix docgen crash on topmenus.inc.

---

compiler/sc1.cpp
compiler/sc5-in.scp
tests/compile-only/fail-methodmap-use-before-decl.sp
tests/compile-only/fail-methodmap-use-before-decl.txt

This partially fixes alliedmodders/sourcemod#897.

Fix assert when using a methodmap before declaring it.

---

compiler/sc1.cpp

Enable -D flag for linux

---

compiler/sc.h
compiler/sc1.cpp
compiler/sc2.cpp
compiler/scvars.cpp

This is in preparation for some large changes to lex().

Various minor build fixes and cleanups.

---

compiler/sc2.cpp

Previously, the lexer would consume characters until it matched a
keyword, and would then commit the new stream pointer. Instead, we
should consume characters up until an entire lexeme is available, and
then deduce whether it is a keyword or symbol.
This unfortunately is a bit tricky since there are lots of special
cases:
'@' is equivalent to 'public' if alone.
'_' is a special token if alone.
'#' can begin a keyword but not a symbol.
'@' can begin a symbol but not a keyword.
Symbols can contain numbers, but keywords cannot.
The new logic handles these cases as the old code did.
The second patch in this series converts the sc_token loop to a hashtable lookup, which is about a 10% improvement in compilation speed.

Refactor symbol and keyword lexing.

---

compiler/assembler.cpp
compiler/lexer.cpp
compiler/libpawnc.cpp
compiler/memfile.cpp
compiler/memfile.h
compiler/sp_symhash.h

This cleans up and reduces memfile usage in the code generation step.

Refactor assembly parsing.

---

compiler/expressions.cpp
compiler/lexer.cpp
compiler/parser.cpp
compiler/sc.h
compiler/sclist.cpp
compiler/scvars.cpp
compiler/scvars.h

A few pointers were allocated without being freed. Fix by using C++
idioms. Also remove NO_DEFINE, that ship has sailed.

Fix memory leaks.

---

compiler/lexer.cpp
compiler/parse-expr.cpp
compiler/sc.h
compiler/sclist.cpp
compiler/sclist.h

Delete the useless duplicatestring method.
Const-qualify a bunch of char pointers.
Don't expose stringpair to callers.

Clean up the subst API.

---

compiler/parser.cpp
tests/compile-only/fail-enum-struct-in-native.txt

Fix incorrect name output in error 135

---

compiler/errors.cpp
compiler/errors.h
compiler/lexer.cpp
tests/compile-only/fail-missing-semi-on-enum-struct.sp
tests/compile-only/fail-missing-semi-on-enum-struct.txt
tests/sourcemod/include/sdktools_trace.inc

Respect #pragma semicolon when requiring newlines.

---

compiler/parser.cpp

When we encounter an unknown method call, we will try to generate a
temporary symbol with a made-up name. If the methodmap has no name,
this will result in a symbol starting with ".", for example,
".SetValue". When finding the display name for this function, the
compiler assumes that a name starting with a non-identifier symbol
is special, and must therefore be an operator. Since operator names have
a different maximum length than normal symbol names, this causes a stack
overflow.
In addition this patch fixes the function that can erroneously overflow.
Bug: fixes issue #333
Test: compile-only/fail-methodmap-keyword-name

Ensure that methodmaps always have a name.

---

compiler/assembler.cpp
compiler/codegen.cpp
compiler/errors.cpp
compiler/expressions.cpp
compiler/lexer.cpp
compiler/libpawnc.cpp
compiler/memfile.cpp
compiler/optimizer.cpp
compiler/parse-expr.cpp
compiler/parser.cpp
compiler/sci18n.cpp
compiler/sclist.cpp
tools/restyler/fix_comments.py

This removes the following comments:
- /* do */
- /* for */
- /* if */
- /* switch */
- /* while */

Remove pointless comments.

---

compiler/messages.h
compiler/parser.cpp
compiler/types.cpp
compiler/types.h
tests/compile-only/fail-redefine-typedef.sp
tests/compile-only/fail-redefine-typedef.txt

Bug: issue #338
Test: tests/compile-only/fail-redefine-typedef.sp

Don't allow redefining typedefs or typesets.

---

compiler/parser.cpp

Remove unused constants.

---

compiler/codegen.cpp
compiler/expressions.cpp
compiler/lexer.cpp

Remove uses of PAWN_CELL_SIZE.

---

compiler/parser.cpp

Bug: issue #370
Test: manual test

Relax name shadowing checks for implicitly prototyped functions.

---

compiler/expressions.cpp
compiler/lexer.cpp
compiler/lexer.h
compiler/parser.cpp
compiler/sc.h

This has never been used, and we don't support goto anyway.
Bug: N/A
Test: builds

Remove the iLABEL identifier type.

---

compiler/expressions.cpp

Remove dead code related to implicit sizeof/tagof in argument lists.

---

compiler/code-generator.cpp
compiler/expressions.cpp
compiler/expressions.h
compiler/name-resolution.cpp
compiler/new-parser.cpp
compiler/new-parser.h
compiler/parse-node.h
compiler/semantics.cpp

fix(docs): license typo

---

compiler/parser.cpp
tests/compile-only/fail-global-array-float-index.sp
tests/compile-only/fail-global-array-float-index.txt

Bug: issue #407
Test: compile-only/fail-global-array-float-index.sp

Fix global array declarations not checking index tags.

---

compiler/lexer.cpp

Bug: issue #413
Test: manual test

Do not mark liveness information from skipped functions.

---

compiler/expressions.cpp
tests/compile-only/fail-assign-scalar-to-array.sp
tests/compile-only/fail-assign-scalar-to-array.txt

Bug: issue #416
Test: compile-only/fail-assign-scalar-to-array

Fix scalars being assignable to arrays.

---

compiler/expressions.cpp
compiler/expressions.h
compiler/semantics.cpp
tests/compile-only/ok-compare-function-to-nullfunc.sp
tests/compile-only/ok-compare-methodmap-constant.sp

Bug: issue #426
Test: compile-only/ok-compare-methodmap-constant

Fix commutative tag checks.

---

compiler/lexer.cpp
compiler/parser.cpp
compiler/sc.h

Remove stacksize from FunctionData.

---

AMBuildScript
compiler/AMBuilder
compiler/parser.cpp
compiler/pawncc.cpp
vm/AMBuilder

Nothing major, just updating the existing Emscripten support for WASM and the latest optimizations.
Debug and Optimised configurations build and pass all compiler and runtime tests.

Assorted Emscripten fixes

---

AMBuildScript
compiler/new-parser.cpp

Bug: issue #516
Test: tests/compile-only/fail-crash-on-redecl-function.sp

Fix crash when redeclaring natives.

---

compiler/parser.cpp
tests/compile-only/fail-warn-new-decls-on-old-array.sp
tests/compile-only/fail-warn-new-decls-on-old-array.txt

Fix newdecl warning on old declaration.

---

compiler/new-parser.cpp
tests/compile-only/ok-sizeof-this.sp

Fix sizeof() not accepting "this" tokens.

---

compiler/parser.cpp
tests/compile-only/fail-bad-string-vector-assignment.sp
tests/compile-only/fail-bad-string-vector-assignment.txt

Fix 2d char vectors being assignable to char arrays.

---

AMBuildScript
compiler/AMBuilder
compiler/assembler.cpp
include/sp_vm_api.h
tools/run_corpus.py
tools/verifier/verifier.cpp
vm/AMBuilder
vm/api.cpp
vm/api.h
vm/environment.cpp
vm/file-utils.cpp
vm/file-utils.h
vm/plugin-runtime.cpp
vm/plugin-runtime.h
vm/smx-v1-image.cpp
vm/smx-v1-image.h

Use this helper to verifier compiler output before writing binaries.
Also, add a binary verification pass to run_corpus.py.

Add full verification helper to IPluginRuntime.

---

compiler/assembler.cpp
compiler/code-generator.cpp
compiler/emitter.cpp
compiler/parse-node.h
compiler/sci18n.h
compiler/scvars.cpp
tests/compile-only/ok-balanced-ternary-array.sp
tools/run_corpus.py
vm/control-flow.h
vm/environment.cpp
vm/method-verifier.cpp
vm/method-verifier.h
vm/plugin-runtime.cpp

Verification bug fixes.

---

compiler/code-generator.cpp
compiler/messages.h
compiler/name-resolution.cpp
compiler/new-parser.cpp
compiler/parse-node.h
compiler/semantics.cpp
tests/compile-only/ok-public-struct-refs-symbol.sp

This fixes a regression from 1.10.

Allow global variables in public structs.

---

compiler/expressions.cpp
compiler/types.cpp
compiler/types.h

Allow characters to be used as array indices.

---

compiler/expressions.cpp
tests/compile-only/ok-contravariant-array-types.sp

Bug: issue #684
Test: ok-contravariant-array-types

Allow contravariant array casts.

---

vm/x86/jit_x86.cpp

Fix register typo in visitHEAP_RESTORE().

---

tools/smxtools/smxdasm/Sections.cs
tools/smxtools/smxdasm/V1Disassembler.cs
tools/smxtools/smxdasm/V1Types.cs
tools/smxtools/smxviewer/MainWindow.cs

This adjusts the output of SmxTools to display more info around debug sections and used code features.

Update smxtools QoL

---

compiler/semantics.cpp
compiler/semantics.h
tests/compile-only/ok-issue697.sp

Set loop_has_break and loop_has_continue.

---

compiler/code-generator.cpp
compiler/code-generator.h

We never filled out code_end in the new debug sections. This was broken
when we stopped reparsing. As a fix, we track when variables leave
scope, and add their debug information then. This should work fine as
debug symbols are re-sorted before getting written to the .smx file.
Bug: issue #700
Test: manual test, smxtools

Fix codeend in debug rtti.

---

compiler/symbols.cpp
tests/compile-only/fail-global-variable-shadowed.sp
tests/compile-only/fail-global-variable-shadowed.txt

Bug: issue #714
Test: fail-global-variable-shadowed

Fix name shadow detection not working.

---

.github/workflows/source-corpus.yml
tools/corpus/download.py
tools/corpus/run.py

This checks out a public repository of source and binary files to test
the compiler and loader against. The intent is to run this on
presubmit/postsubmit for master. It's not needed on branches since we
don't take major changes there.

Automate corpus testing.

---

compiler/name-resolution.cpp
tests/compile-only/fail-redefine-public-after-forward.sp
tests/compile-only/fail-redefine-public-after-forward.txt

Fix crash when forward is defined twice as public function.

---

compiler/parser.cpp
tests/compile-only/fail-crash-on-invalid-function-prototype.sp
tests/compile-only/fail-crash-on-invalid-function-prototype.txt

Fix crash on invalid function prototype.

---

compiler/semantics.cpp
tests/compile-only/fail-call-primitive-value.sp
tests/compile-only/fail-call-primitive-value.txt

Fix crash on invalid call.

---

compiler/semantics.cpp
tests/compile-only/fail-undefined-symbol-in-default-assignment.sp
tests/compile-only/fail-undefined-symbol-in-default-assignment.txt

Bug: issue #771
Test: new test

Fix crash when default assignment has an error.

---

compiler/semantics.cpp
tests/compile-only/ok-dtor-accessor.sp

Mark accessors as used in a delete stmt.

---

compiler/parser.cpp
tests/compile-only/fail-name-in-typeset-type.sp
tests/compile-only/fail-name-in-typeset-type.txt

Fix infinite loop on malformed typeset.

---

compiler/errors.cpp
tests/compile-only/file-reporting/fail-main.sp
tests/compile-only/file-reporting/fail-main.txt
tests/compile-only/file-reporting/ignore-otherfile.sp
tests/runtests.py

Fix file number inference in error reporting.

---

compiler/parser.cpp
tests/compile-only/fail-empty-preproc-expr.sp
tests/compile-only/fail-empty-preproc-expr.txt

Fix crash on empty preproc expression.

---

compiler/semantics.cpp
tests/compile-only/ok-no-warning-on-assign-multiply.sp

Fix incorrect warning on variable self-multiply.

---

compiler/array-helpers.cpp
compiler/code-generator.cpp
compiler/code-generator.h
compiler/main.cpp
compiler/messages.h
compiler/sc.h
tests/compile-only/fail-array-almost-too-big.sp
tests/compile-only/fail-array-almost-too-big.txt

Bug: issue #850
Test: test suite

Fix codegen error on huge array allocation.

---

compiler/semantics.cpp
tests/compile-only/fail-unindexed-array-in-test.sp
tests/compile-only/fail-unindexed-array-in-test.txt

Bug: fixes issue #878
Test: new test

Fix missing error on unindexed arrays in logical expressions.

---

compiler/messages.h
compiler/semantics.cpp
tests/compile-only/fail-struct-with-bad-initializer.sp
tests/compile-only/fail-struct-with-bad-initializer.txt

Bug: issue #860
Test: new test

Fix crash on invalid struct declaration.

---

compiler/messages.h
compiler/parser.cpp
tests/compile-only/fail-ctor-with-return-type.sp
tests/compile-only/fail-ctor-with-return-type.txt

Bug: issue #880
Test: new test

Fix crash on malformed constructor declarations.

---

compiler/parser.cpp
compiler/semantics.cpp
compiler/semantics.h
tests/compile-only/ok-binary-expression-in-preproc.sp

Bug: issue #889
Test: new test

Fix warning when using binary expressions in the preprocessor.

---

compiler/lexer.cpp

If we had any lookahead tokens queued up when entering a new file, they should be lexed after the file has been fully parsed. Normally this condition is not possible to hit because there's no lookahead before `#include` tokens.

Before entering a file, save any lookahead tokens.

---

compiler/semantics.cpp
tests/compile-only/fail-array-extra-indices.sp
tests/compile-only/fail-array-extra-indices.txt

Fix invalid array index causing assertion.

---

compiler/array-helpers.cpp
compiler/code-generator.cpp
compiler/messages.h
compiler/name-resolution.cpp
compiler/parse-node.h
compiler/semantics.cpp
compiler/semantics.h
compiler/types.cpp
compiler/types.h
include/sp_vm_types.h
tests/compile-only/fail-bad-array-decls.txt
vm/environment.cpp
vm/plugin-context.cpp

There was a lot of duplication here, and fixed and dynamic array behavior is pretty similar.

Unify fixed and dynamic array initialization.

---

compiler/array-helpers.cpp
compiler/name-resolution.cpp
tests/compile-only/fail-array-decl-with-zero-enum-value.sp
tests/compile-only/fail-array-decl-with-zero-enum-value.txt

Improve error reporting for field types with invalid dimensions.

---

compiler/semantics.cpp
compiler/semantics.h
tests/compile-only/ok-this-as-non-const.sp

This is a huge hack that will hopefully become cleaner in the IR model.
Bug: issue #993

Fix "const this" in enum struct methods.

---

compiler/semantics.cpp
tests/compile-only/ok-enum-struct-param-implicit-read.sp

Fix erroneous warning on enum struct parameters.

---

compiler/lexer.cpp
tests/compile-only/ok-nested-preproc-if.sp

Bug: issue #989
Test: new test csae

Fix nested #if 0 not working.

---

compiler/name-resolution.cpp
tests/compile-only/fail-inherit-undeclared-methodmap.sp
tests/compile-only/fail-inherit-undeclared-methodmap.txt

Fix crash when inheriting from an undeclared methodmap.

---

compiler/parser.cpp
tests/compile-only/fail-incomplete-property-block.sp
tests/compile-only/fail-incomplete-property-block.txt

Fix hang on unterminated property decls.

---

compiler/semantics.cpp
compiler/semantics.h
tests/compile-only/fail-stock-array-unused.sp
tests/compile-only/fail-stock-array-unused.txt
tests/compile-only/fail-stock-var-unused.sp
tests/compile-only/fail-stock-var-unused.txt
tests/compile-only/ok-included-stock-array-unused.inc
tests/compile-only/ok-included-stock-array-unused.sp
tests/compile-only/ok-included-stock-var-unused.inc
tests/compile-only/ok-included-stock-var-unused.sp

Bug: issue #976
Test: new test cases

Fix erroneous warning on unused stock variables.

---

compiler/expressions.cpp
tests/compile-only/fail-ref-compare-function-signature.sp
tests/compile-only/fail-ref-compare-function-signature.txt

Bug: issue #992
Test: new test cases

Fix bugs in function signature type checking.

---

compiler/code-generator.cpp
tests/enum-structs/return-enum-struct.out
tests/enum-structs/return-enum-struct.sp

Fix returning enum structs not working.

---

tests/regressions/switch-with-int-min-case.out
tests/regressions/switch-with-int-min-case.sp
vm/x86/jit_x86.cpp

Fix switch statements not working when one case is INT_MIN.
