alliedmodders/sourcepawn

- compiler/sc2.cpp
- compiler/sc5-in.scp
Looks like these got missed when moving the fatal errors to an enum.
@dvander
> Fix #assert and #error using the wrong error numbers

- compiler/sc1.cpp
int a[5], b;
b would get a size of |0| on the stack instead of a sizeof(cell_t).
Bug: https://bugs.alliedmods.net/show_bug.cgi?id=6335
> Fix declaring variable on same line after array

- compiler/sc1.cpp
```sourcepawn
new String:INVISIBLE[2][8];
```
Multidimensional arrays like this wouldn't get their debug info added to
the debug symbols table.
Bug: https://bugs.alliedmods.net/show_bug.cgi?id=6324
See Fyren's comment in the bug report.
This patch recursively checks the parent symbol of array dimensions
until it finds the top symbol and uses that to check for the compound
level.
This still allows for early exiting the loop when going out of scope.
> Add missing debug info for multidimensional strings

- compiler/sc.h
- compiler/sc3.cpp
- compiler/tests/disabled/this-eval-ordering.sp
This is a super nasty bug. Pawn evaluates function arguments in left-to-right order, then takes each chunk of code that was evaluated and reverses the chunks, so that they are magically pushed in the right order.
Unfortunately, this breaks situations where `this` is computed off a register, i.e. when it's evaluated as an expression result or array slot. We don't consider the full evaluation of `this` as an actual argument (nor, can we), so it doesn't get reordered, and the register it's in can be destroyed by the chunk reordering.
The fix for this is based on feedback from Fyren and asherkin. Now, we detect whether `this` is being held in a register. If it is, we evaluate it before processing any arguments, then push it. After we evaluate each argument, we pop the `this` value, push the …
> Fix bug where complex |this| values could be corrupted while evaluating function arguments. (bug 6329)

- compiler/sc.h
- compiler/sc3.cpp
- compiler/sc4.cpp
If a |this| was computed off an expression, then it's not actually an l-value. I forgot to do an l-value check before calling rvalue().
For good measure I made a new wrapper around rvalue() that also resets l-value bits when evaluating an accessor.
> Fix a regression when using accessors as |this|.

- vm/x86/jit_x86.cpp
This is an unfortunate and nasty bug. When invoking ReportError from the JIT, we leave the code in `eax` and don't restore it after the call. So the value returned from the JIT in the case of an internal error is essentially random.
I only noticed it because I saw the HEAPLOW check double-reporting, since Execute2() will manually report this error if the JIT returned err=0 but HLW fails a sanity check.
> Fix internal error codes not propagating back to Execute2.

- compiler/sc1.cpp
Stupid bug. The compiler stores an index for each loop indicating the current position of the "stack usage" tracker. When a "continue" keyword is encountered, we generate stack restores for everything newer than this index.
There is a separate tracker for heap usage, but the same index is expected to work in both. Whenever we enter a new nesting level in the stack usage tracker, we must also enter one in the heap usage tracker.
> Fix loops not freeing heap-allocated variables when using continue or break.

- exp/compiler/lexer.cpp
\x2A in Strings and chars wouldn't be replaced by the corresponding character *.
> Fix handling of escaped hex chars \xHH

- compiler/sc1.cpp
- compiler/sc3.cpp
- compiler/sc4.cpp
SYSREQ_C is an older opcode for invoking natives that doesn't guarantee a static number of arguments at the callsite. It's pretty much junk, but of course, it is emitted by default. We rely on the peephole optimizer rewriting it into the much superior SYSREQ_N.
This patch replaces SYSREQ_C generation with SYSREQ_N so there is no chance of emitting it again.
I tried by hand to create code that emits SYSREQ_C past the peephole optimizer, but couldn't manage. I know it's possible, as I've seen it in the wild, which is unfortunate since I'd like to kill it off in the JIT too. Instead I'll just try to deprecate it, in that it won't be able to invoke newer natives.
> Kill off SYSREQ_C.

- vm/api.cpp
- vm/code-allocator.cpp
- vm/code-allocator.h
- vm/code-stubs.cpp
- vm/code-stubs.h
- vm/compiled-function.cpp
- vm/compiled-function.h
- vm/environment.cpp
- vm/environment.h
- vm/x86/code-stubs-x86.cpp
- vm/x86/jit_x86.cpp
- vm/x86/x86-utils.cpp
- vm/x86/x86-utils.h
This is a replacement for our older, more complicated executable code allocator. The previous allocator kept a free list and searched free lists for matching allocations.
The new allocator keeps a small cache of recently used memory pools, and finds a best fit within the free space of those pools. We no longer track free regions.
Code allocation now returns an object which reference counts the underlying pool. This should be less error-prone than the old FreePageMemory() API. The older API is now a wrapper.
> Add a new executable allocator.

- compiler/libpawnc.cpp
- compiler/sc.h
- compiler/sc3.cpp
A few methodmap fixes ago, we encountered a problem: spcomp evaluates arguments left-to-right, then reverses their evaluation order. The value of `this` is always computed first, and is never re-ordered. If the value of `this` depends on the value of a register, then argument evaluation can destroy it.
To fix this, we detected when the value of `this` was at risk, and started shuffling it down the stack as each argument evaluated. That worked, except, we forgot to carry that solution over to default values.
This fix comes in two parts. The first part attempts to extract a lot of the argument/stack manipulation out into a separate class. This doesn't change any behavior (I hope). The second part actually fixes the bug.
> Fix complex this-values not being preserved across default arguments.

- compiler/sc1.cpp
- compiler/sc5-in.scp
- compiler/tests/fail-bad-array-initializer.sp
- compiler/tests/fail-bad-array-initializer.txt
With some corrupt array initializers, an assert guarding a null deref fires. In a release build it crashes. Since initials2() is just horrible I'm going to paper over this. With the test case in the bug it errors anyway.
> Fix crash with corrupt array initializers. (bug 6378)

- compiler/sc3.cpp
Since `view_as<>` is parenthesized, we can use the highest level of precedence for parsing the expression inside the parenthesis.
> Fix view_as<> precedence. (bug 6380)

- compiler/sc.h
- compiler/sc1.cpp
- compiler/sc2.cpp
- compiler/sc3.cpp
- compiler/sc6.cpp
- compiler/sctracker.cpp
- compiler/sctracker.h
We removed multitag support in SourcePawn. The compiler still tracks tags as a vector, but the vector is at most length 1. This patch removes tag vectors and replaces them with a scalar.
For cases that looked for `numtags < 1`, that check is now `tag == 0`.
> Remove all symbolic references to "numtags" or tag vectors.

- compiler/sc.h
- compiler/sc1.cpp
- compiler/sc2.cpp
- compiler/sc3.cpp
- compiler/sc4.cpp
- compiler/sc5-in.scp
- compiler/sc6.cpp
- compiler/sc7-in.scp
- compiler/scvars.cpp
The JIT doesn't support about 20-30 opcodes. Most aren't ever generated. This patch ensures this by taking them out of the assembler tables, and removing any code that could have generated those ops.
> Nuke opcodes that can't be generated.

- vm/shell.cpp
- vm/smx-v1-image.cpp
1. The "out of memory" error could never be triggered on allocation failure due to new throwing instead of returning NULL.
2. Tampering with the SMX container could cause inflate() to crash (initially this was an equality check, but I found a single binary on the forums where the file was 1 byte larger than disksize).
@dvander
> Additional checks for SMXv1 validation

- compiler/sc1.cpp
- compiler/sc3.cpp
GDB appears to agree that these are functionally identical, although that charmax constant appears to be incorrect...
@dvander
> Fix -Wshift-negative-value warning in Clang 3.8

- include/sp_vm_api.h
- vm/base-context.cpp
- vm/base-context.h
- vm/environment.cpp
- vm/environment.h
- vm/plugin-context.cpp
- vm/scripted-invoker.h
This modifies a few interfaces, so I bumped both versions.  I have no idea if both need bumping.
IPluginFunction: adds const char \*DebugName()
IErrorReport: adds int Code() and IPF \*Blame()
IPluginContext: adds BlamePluginError(IPF\*, const char\*, ...)
ScriptedInvoker's existing FullName() was changed to DebugName().  It lost some constness since no other IPluginFunction stuff was.
There'll be another PR for SM to use this instead of ThrowNativeError where applicable and update DebugReporter.
> Allow blaming an IPF for an error.

- vm/smx-v1-image.cpp
- vm/smx-v1-image.h
This breaks a couple of increasingly-common binary modifications to deter Lysis.
I'm thinking we should also be more opinionated here and require *all* the sections we expect to exist, and start warning on load for v1.0 SMX versions (without any debug info) - with the aim to eventually kill those off as well.
Review: @dvander @KyleSanderson
CC: @GoD-Tony @peace-maker
> Validate .tags section.

- exp/docgen/README.md
Had to do this on my local setup, might as well have it in the readme.
> Add nginx routing rules to docgen readme

- exp/docgen/www/template/enum.php
Other values across the site use monospace font.
> Use monospace font for enum values

- compiler/sc.h
- compiler/sc1.cpp
- compiler/sc2.cpp
- compiler/sc3.cpp
- compiler/tests/ok-no-warning-on-unused-param.sp
- compiler/tests/runtests.py
- exp/compiler/pool-allocator.cpp
- exp/compiler/pool-allocator.h
This is a quick, surgical fix: A new usage flag, uCALLBACK, which tells doarg to treat callback arguments as if the function were public.
> Fix an unused arg warning.

- compiler/sc2.cpp
Amended ::btoi documentation to note that this function attempts to parse binary literals, not boolean (true/false, which are instead constants in SourcePawn)
Original bug report:
https://bugs.alliedmods.net/show_bug.cgi?id=6498
> Amended ::btoi(cell, unsigned char*) documentation

- compiler/sc.h
- compiler/sc2.cpp
Added support for octal literals using 0o prefix notation.
This is a replacement for PR #62 
Original report:
https://bugs.alliedmods.net/show_bug.cgi?id=6319
> Added support for octal literals

- vm/x86/jit_x86.cpp
In bug 5841 we started using SSE, which implicitly switched our rounding mode on most machines to half-even tie-breaking, rather than half-up. The x87 code is broken anyway (see alliedmodders/amxmodx#376), so let's just simplify it.
> Remove half-up rounding in x87 FPU code.

- compiler/sc1.cpp
- compiler/sc3.cpp
- compiler/sc5-in.scp
Not sure if this is all that's necessary.
> Make casting a void function illegal, make returning a value from a void function illegal (bug 6492)

- vm/x86/assembler-x86.h
- vm/x86/jit_x86.cpp
Again from alliedmodders/amxmodx#376 - our round to ceil implementation is broken for very large integers. To fix this I did the conversion on a 64-bit integer instead, and then added a check to see if it overflowed.
> Fix ceil rounding for very large integers.

- compiler/sc1.cpp
- compiler/tests/ok-ref-as-index.sp
gcc 4.9 yelled at me about the variables.
> Fix references as dimension sizes and get rid of a couple unused variables (bug 6452)

- AMBuildScript
- compiler/sc1.cpp
- compiler/sc2.cpp
- exp/compiler/AMBuilder
- exp/compiler/ast.h
- exp/tools/docparse/docparse.cpp
- vm/scripted-invoker.h
Didn't clean up the unused stuff in `exp/` as I presume it is there for future dev, moved them to `-Wno-error=` so the warnings are visible however. Also corrected the version check for `-Wno-delete-non-virtual-dtor`.
@dvander
> Unsilence and fix a number of warnings.

- compiler/sc3.cpp
- compiler/tests/fail-methodmap-arg-error-pos.sp
- compiler/tests/fail-methodmap-arg-error-pos.txt
The error message for bad arguments reports the bad argument's position.  This is off by one for methodmap calls.
> Fix reported position of bad arguments in methodmap function calls.

- vm/environment.cpp
> Exception handler stack is not initialized on startup.

- vm/AMBuilder
- vm/compiled-function.cpp
- vm/compiled-function.h
- vm/environment.cpp
- vm/jit.cpp
- vm/jit.h
- vm/outofline-asm.h
- vm/plugin-context.cpp
- vm/pool-allocator.cpp
- vm/pool-allocator.h
- vm/x86/jit_x86.cpp
- vm/x86/jit_x86.h
This is a quick and dirty abstraction to replace the manual CallThunk/ErrorPath machinery that does delayed codegen in the JIT. This will make it much easier to add more custom error messaging, for example, recording BOUNDS instructions without yet another one-off vector of specialized structs.
> Add out-of-line codepath abstraction

- vm/jit.cpp
- vm/x86/assembler-x86.h
- vm/x86/jit_x86.cpp
- vm/x86/macro-assembler-x86.h
When we take an error path, we don't guarantee that the stack is 16-byte aligned. Normally this isn't an issue, but CompileFromThunk leaves an extra word on the stack (it floats a return address), and if it reports an error, the formatting routine can crash if it hits a MOVAPS or something else that relies on ABI alignment.
This patch forces the stack to be aligned on error paths. Since we don't really care about the exact stack contents (just the ability to walk frames), it shouldn't be a problem. I also added a debug-only trap that will fire if the stack is unaligned before a call.
> Fix stack alignment issues on error paths.

- vm/AMBuilder
- vm/api.cpp
- vm/environment.cpp
- vm/environment.h
- vm/jit.cpp
- vm/jit.h
- vm/method-info.cpp
- vm/method-info.h
- vm/null-frame-layout.h
- vm/plugin-context.cpp
- vm/plugin-runtime.cpp
- vm/plugin-runtime.h
- vm/scripted-invoker.cpp
- vm/scripted-invoker.h
- vm/stack-frames.cpp
- vm/stack-frames.h
- vm/x86/code-stubs-x86.cpp
- vm/x86/jit_x86.cpp
- vm/x86/macro-assembler-x86.h
These patches have two main refactorings. One, a new "MethodInfo" class sits in between PluginRuntime and CompiledFunction. This lets us cache method stuff not specific to the JIT, such as invalidation results.
Second, FrameIterator is now understands that there may be multiple execution engines. It only knows how to iterate over InvokeFrames, which can be subclassed. To iterate over inline frames (i.e., function calls), it allocates an instance of InlineFrameIterator which is specific to the invocation type. A JitInvokeFrame's contents can be iterated with a JitFrameIterator.
> Factor JIT-specific information out of methods and frames.

- compiler/sc7-in.scp
- include/smx/smx-v1-opcodes.h
- vm/method-verifier.cpp
- vm/pcode-reader.h
- vm/pcode-visitor.h
- vm/x86/jit_x86.cpp
- vm/x86/jit_x86.h
An analysis of every .smx file on the forums and webcompiler cache reveals no instances of IDXADDR.B or LIDX.B.
These opcodes are only present in the peephole optimizer. They usually sequence from "shl.c.pri; load.i" pairs, which are never generated. If we're going to shift by a weird amount and then load, we always generate LODB.I.
This patch removes them.
> Remove ungenerated LIDX.B and IDXADDR.B opcodes.

- tests/runtests.py
- tools/testing/test-runtime.bat.in
- tools/testing/test-runtime.sh.in
- vm/plugin-runtime.cpp
- vm/plugin-runtime.h
- vm/shell.cpp
Some quick changes to runtime testing. First, a hack to enable float opcodes in the shell. Later on we'll just tear these out of SM and hoist them into SP directly, but for now we just mark the natives as bound so replacement will work.
Next, some opcodes are only generated when not using the peephole optimizer. We should test -O0 as well just for better coverage.
> Enhance runtime testing.

- tests/exceptions/array-out-of-bounds.out
- vm/x86/jit_x86.cpp
- vm/x86/macro-assembler-x86.h
This also fixes CIP mapping - unfortunately this gets handled quite manually right now.
> Fix stack alignment in out-of-bounds reporting.

- vm/api.cpp
- vm/api.h
GetEngineName now adds some extra goo to describe the runtime engine. This broke SourceMod builds.
> Fix GetEngineName on SourceMod builds.

- vm/base-context.cpp
SourceMod uses it e.g. to indicate parameter count mismatches in
forwards like `pContext->ThrowNativeErrorEx(SP_ERROR_PARAMS_MAX, NULL);`
sprintf doesn't like the msg/format string to be NULL.
> Fix crash in ThrowNativeErrorEx with msg = NULL

- compiler/sc1.cpp
Code like:
`if ("") // blabla`
or
`if ({1,2}) // bla`
causes an "array must be indexed" error and crashes when it tries to
print the variable name of the array - because there is none for a
constant inline array.
This patch just prints nothing for the variable name.
> Fix compiler crash on inline arrays in conditions

- vm/method-verifier.cpp
- vm/method-verifier.h
It's not allowed to jump outside the function. The end of the function
is only known after it has been completely verified, so add a check for
the highest jump target after we know the end.
> Detect jumps past the end of the function

- vm/method-verifier.cpp
- vm/method-verifier.h
Copy & paste error in validation of `sysreq.n` parameter count.
`nparams` is the number of parameters passed, not some address.
The `genarray` validation used the same validation logic, but the
`ndims` are the number of dimensions to be generated instead of an
address.
> Fix parameter count validation

- compiler/sc1.cpp
- compiler/sc3.cpp
- compiler/tests/fail-jagged-sizeof.sp
- compiler/tests/fail-jagged-sizeof.txt
This change is from upstream.
The old code only considered the first innermost array when counting the size of the final dimension.  This breaks in cases like this:
```
char arr[3][2][] = {
{"123", "123"},
{"1234","1234"},
{"123", "123"}
}
```
The compiler would assume the last dimension was sized one cell/four chars and not indeterminate.  This results in the indirection vectors being wrong.
I'll add some tests before merging.
> Fix counting of unspecified final dimensions of arrays.

- compiler/sc3.cpp
Similar to https://github.com/alliedmodders/amxmodx/pull/372
Option ```-Wmisleading-indentation``` has been introduced in GCC 6 and it's enabled by ```-Wall```. Due ```-Werror``` option we're unable to successfully build SourcePawn using GCC.
> Fix compilation for GCC6

- include/sp_vm_api.h
- vm/environment.h
Give listeners more information about the cause of the error, so they
can choose which error to log.
> Expose error code in IErrorReport

- vm/method-verifier.cpp
The compiler never emits this instruction, so don't allow it in a binary.
@asherkin did a test against all uploaded .smx files in the forum to confirm.
> Disallow |halt| instruction

- exp/compiler/lexer.cpp
- exp/compiler/lexer.h
If we didn't have to deal with macros, this would be a convincing case to use an auto-generated lexer.
> 4:30 PM <Peace-Maker> https://github.com/peace-maker/botmimic/blob/master/scripting/include/botmimic.inc that one never finishes unless i add a newline to the end
> 4:51 PM <dvander> Peace-Maker: bug is, say you consume the last char. then you try to read another and it's not what you expect, so you backtrack
> 4:51 PM <dvander> but backtracking loses the fact that you hit EOF soy ou keep reading the same token forever
> Fix infinite loop scanning in the experimental parser.

- exp/compiler/tk-evaluator.cpp
This looks like a bug, we actually do intend to expand the macro but we have to spot-enable it, since it is always disabled normally (so we don't expand the input to the defined operator).
> Fix macro expansion when evaluating preprocessor expressions. (bug 6582)

- compiler/sc.h
- compiler/sc1.cpp
- compiler/sc3.cpp
- compiler/sc7.cpp
- compiler/sctracker.h
- include/sp_vm_types.h
- vm/method-verifier.cpp
`sARGS_MAX` becomes `SP_MAX_EXEC_PARAMS` and `sMAXARGS` becomes `SP_MAX_CALL_ARGUMENTS` in the VM as well as the compiler.
The method verifier now checks for the maximum allowed arguments of a call,
which differs from the maximum number of parameters when declaring a function in the compiler.
The present name `SP_MAX_EXEC_PARAMS` doesn't really describe the value, but it would require changes to SourceMod too to make it more descriptive.
> Unify parameter count defines in VM and compiler (bug 6540)

- vm/environment.cpp
- vm/shell.cpp
Diff is a mess, but this one is fairly simple - Environment::Invoke was missing a check on jit_enabled_.
> Fix DISABLE_JIT option to spshell

- compiler/sc6.cpp
- compiler/tests/fail-unused-call-with-undefined-call.sp
- compiler/tests/fail-unused-call-with-undefined-call.txt
This is probably a regression from when we made all functions implicitly public. The code that builds the name/address table in the header, assumes that functions marked as `uREAD` can be exported. But in fact a function can be `uREAD | uMISSING` which means it was declared and used, but not defined. This is not a compiler error if the usage happened in a function that was omitted in the second pass.
> Fix adding function table entries for functions with no definition. (bug 124, r=fyren)

- vm/plugin-runtime.cpp
The full path is passed but not saved.
> Fix typo when caching plugin file names

- compiler/sc.h
- compiler/sc1.cpp
- compiler/sc2.cpp
- compiler/sc5.cpp
- compiler/sclist.cpp
- compiler/tests/fail-delete-no-dtor.sp
Currently an unused function is reported on the last line of a file instead of the line in the file of the declaration.
Line numbers could get confused too if there is an unused function and an unused variable in one file.
plugin.sp(22) : warning 203: symbol is never used: "func"
This is a ported fix from upstream Pawn https://github.com/compuphase/pawn/commit/584901e179e07f7efb8d4f77d372a3236f515b6a
> Report file (and line) of the declaration of unused variables/functions

- tools/testing/test-all.bat.in
- tools/testing/test-runtime.bat.in
Even if there is a failing test case in the compiler tests the test-all.bat script would have an exit code of 0 if the runtime tests all passed afterwards.
Batch variables are global by default, so the test-runtime.bat script overwrote the `status` variable in the test-all.bat script.
> Fix test suite overwriting compiler test result on windows

- compiler/sc.h
- compiler/sc3.cpp
- compiler/sc4.cpp
- compiler/tests/fail-index-array-with-const-negative.sp
- compiler/tests/fail-index-array-with-const-negative.txt
- tests/exceptions/negative-array-index-1.err
- tests/exceptions/negative-array-index-1.out
- tests/exceptions/negative-array-index-1.sp
- tests/exceptions/negative-array-index-2.err
- tests/exceptions/negative-array-index-2.out
- tests/exceptions/negative-array-index-2.sp
- tests/exceptions/negative-array-index-3.err
- tests/exceptions/negative-array-index-3.out
- tests/exceptions/negative-array-index-3.sp
- vm/runtime-helpers.cpp
When the compiler knows the size of an array, an index into the array will be protected by a `BOUNDS n` opcode. This forces the index to be within `[0, n)`. If the compiler doesn't know the size of an array, it gives up and there is no protection. As a result, when passing arrays as parameters, it is possible to unintentionally read garbage data with negative indices. This can mask real bugs and needs to be fixed.
We (ideally) should do this without a new opcode, since that requires a breaking ABI change. The easiest solution, I think, is to just always emit a `BOUNDS` opcode. If we don't know the actual bounds we can emit `INT_MAX`, effectively guaranteeing that only negative numbers will fail the check. This is pretty straightforward and the only gotcha was having to update an error …
> Disallow negative indices in all array access patterns

- .travis.yml
- AMBuildScript
- compiler/AMBuilder
- configure.py
- exp/compiler/AMBuilder
- exp/tools/docparse/AMBuilder
- third_party/zlib/AMBuilder
- tools/testing/Testing.ambuild
- vm/AMBuilder
While attempting to port the SourceMod build scripts to the 2.1 API for the 64-bit port, I realized this needed to be switched first.
> Switch to AMBuild 2.1 API

- AMBuildScript
- configure.py
- vm/interpreter.cpp
- vm/interpreter.h
- vm/jit.cpp
- vm/jit.h
- vm/opcodes.cpp
- vm/pcode-reader.h
- vm/pcode-visitor.h
- vm/x86/jit_x86.cpp
- vm/x86/jit_x86.h
Functions are required to start with OP_PROC since it pushes a frame. But it's not a real opcode - it's special-cased everywhere. This formally drops it from PcodeVisitor.
> Treat OP_PROC as metadata instead of an opcode.

- compiler/AMBuilder
- compiler/sc.h
- compiler/sc1.cpp
- compiler/sc2.cpp
- compiler/sc3.cpp
- compiler/sc6.cpp
- compiler/sctracker.cpp
- compiler/sctracker.h
- compiler/types.cpp
- compiler/types.h
Pawn's original tag system basically worked, but when we extended it for funcenums in SourceMod Alpha, we made a terrible mistake. We did not create a distinction between "tags" and "types". Instead, we annotated tags with a bits that denoted extended type information.
The problem with this was that internally, type information got stored on a "first-come, first-see" basis. If the name `Handle` was used before its definition, that was okay - functions just wouldn't have the definition available, because it wasn't part of the tag bits yet.
Things get weirder because of how spcomp has a two-pass system that preserves tags and global functions signatures. On the second pass, we would have seen definitions for internal types, but that information would still not be available to methods. …
> Remove the internal distinction between tags and types.

- compiler/sc3.cpp
- compiler/sc3.h
sc3.cpp is the heart of the compiler, and it's absolutely insane. Just bonkers. This is a small initial attempt at cleaning it up. Most of the global static methods get moved into an ExpressionParser class, and some of the very complicated cases of hier2() get moved into their own methods.
> Cleanup sc3.cpp

- compiler/sc.h
- compiler/sc1.cpp
- compiler/sc3.cpp
- compiler/sc6.cpp
I don't know what this is or whether it ever even existed. It's never used in any way, but there are lots of checks for it. It's possible faluco or I added it before SM, during the initial JIT sprint.
My guess is it's supposed to be analogous to iREFARRAY or iREFERENCE, but the necessity of those is dubious to begin with.
> Remove iREFFUNC.

- compiler/AMBuilder
- compiler/expression-parsing.cpp
- compiler/expression-parsing.h
- compiler/sc.h
- compiler/sc3.cpp
- compiler/sc3.h
This set of patches moves sc3.cpp helpers into a separate file, so sc3.cpp "only" contains the parser.
> More sc3.cpp cleanup.

- compiler/libpawnc.cpp
- compiler/sc.h
- compiler/sc1.cpp
- compiler/sc5.cpp
- compiler/sc5.h
As is a theme with spcomp, error handling concerns in sc5.cpp are very poorly separated. It has multiple fields of global state that are mutated/consumed at seemingly random times. The way messages are formatted is not centralized (and is indeed duplicated), and everything is interleaved with the lexer/parser's behavior.
These patches separates everything, such that the concept of an "error report" is independent of "displaying an error." The error() function now creates an `ErrorReport` object which is passed to `report_error`. State that used to be global has been removed or moved to ErrorReport.
As a consequence I've removed what I've always considered a terribly confusing feature: line number ranges. The upstream compiler will mark the beginning and ends of expressions so as to not …
> Clean up sc5.cpp.

- vm/AMBuilder
- vm/api.cpp
- vm/assembler.h
- vm/environment.cpp
- vm/environment.h
- vm/macro-assembler.h
- vm/stack-frames.cpp
- vm/stack-frames.h
- vm/x64/assembler-x64.cpp
- vm/x64/assembler-x64.h
- vm/x64/code-stubs-x64.cpp
- vm/x64/constants-x64.h
- vm/x64/frames-x64.h
- vm/x64/macro-assembler-x64.cpp
- vm/x64/macro-assembler-x64.h
Using a fake native on x64 with the interpreter crashes in <tt>SourcePawnEngine::FreePageMemory</tt>. In order to make this work, code needs to be generated for a fake native stub. I've taken some of the existing code from the x64 branch to make this happen.
> Add x64 support for fake natives.

- compiler/AMBuilder
The default include folder isn't being used by the compiler on macOS because it tries to use binreloc instead. The binreloc code only works on Linux since it reads from /proc which doesn't exist on macOS.
> Fixed inclusion of default include folder on macOS.

- compiler/sc7-in.scp
```
if (!func())
```
Gives
```
not
jzer n
```
It has to replace to
```
jnz n
```
> Add "not" optimization.

- vm/x86/jit_x86.cpp
Next step is removing the code paths that can emit reachable `halt`'s from spcomp (exit, sleep, and assert), but this fixes the crash for now.
For shell use it might be nice to have these work (and just map `halt` through to `SetFailState` for SM), but that is a discussion for the future.
Fixes #174
> Align JIT HALT implementation with Interpreter and Verifier

- compiler/sc1.cpp
- tests/basic/genarray.out
- tests/basic/genarray.sp
Initializing a string on the heap using
```
char[] str = "this is a value";
// NOT |char str[] = "this is a value";| which is on the stack
```
wasn't copying the correct string.
Add a test to catch this from now on.
Fixes https://github.com/alliedmodders/sourcemod/issues/760
> Fix initialization of dynamic char[]

- compiler/AMBuilder
- vm/AMBuilder
- vm/code-stubs-null.cpp
- vm/environment.cpp
Requires alliedmodders/ambuild#56 to be useful.
After the changes in #157, CodeStubs were required everywhere, breaking Emscripten support.
I don't think there is any reasonable way for Emscripten to support this properly, so this just creates an asserting, empty CodeStubs impl for it to use.
It seems to me like the interpreter path should never require runtime code generation however (else we'll never be able to work properly on iOS for instance), so it would be nice to have a fallback that works on all platforms if possible - but I do not think I understand the requirements here enough to implement one yet.
> Fix Emscripten support

- .travis.yml
- exp/compiler/preprocessor.cpp
- tools/travis-download-compiler.sh
This PR adds Emscripten build/test to Travis CI.
Due to incompatibilities with the Travis environment and the prebuilt Emscripten SDK, this is using a built-for-Travis `emsdk` from the Urho3D project - which I trust.
The Emscripten builds are fairly slow (especially for debug), but with the other improvements it is only about an extra minute to total build time. Builds are ordered for optimal running time when Travis is running normally, but still getting important results quickly if overloaded.
> Test Emscripten build on Travis

- compiler/sc7.cpp
Avoids multiple `strlen` calls.
> Improve stgwrite

- compiler/sc1.cpp
- compiler/sc6.cpp
Introduces `dumpdup` opcode (compiler only). It helps with huge arrays with default values by creating only 1 `dumpdup` opcode instead of many `dump` opcodes together with a lot of vaues. Array indirection tables still use `dump` though, but they are small in size compared to the array data itself.
The following array:
```SourcePawn
bool x[32][1024][1024];
```
compiles in ~1.7s with this patch instead of ~9.5s on my machine.
> Optimize compilation for large global arrays

- vm/interpreter.cpp
> Fix register increment/decrement visit

- compiler/sc.h
- compiler/sc1.cpp
- compiler/sc3.cpp
- compiler/sc6.cpp
- compiler/sctracker.cpp
- compiler/sctracker.h
- exp/compiler/smx-builder.cpp
- include/smx/smx-headers.h
- tests/runtests.py
- tools/testing/test-runtime.sh.in
- vm/legacy-image.h
- vm/plugin-context.cpp
- vm/plugin-context.h
- vm/smx-v1-image.cpp
- vm/x86/jit_x86.cpp
The way RETN works is pretty lame. The compiler is responsible for balancing the stack and heap, despite the fact that the VM can already trivially do that. In fact, the VM *does* do it. The correct sp/hp values are restored after an exception, since the RETN instruction would never be reached.
This balancing requirement makes it harder to improve the compiler, since we have to emit an epilogue at every return site, which places a useless bookkeeping restriction and generates unnecessary bytecode.
There's an argument that requiring a balanced stack at RETN helps catch compiler bugs, but I'd argue those bugs aren't really important. Codegen leaks will be caught if they matter - inside loops, or with recursion. And codegen leaks are extremely rare. We've only had one that I know of, and it …
> Expand the semantics of the RETN instruction

- compiler/sc1.cpp
- compiler/sc2.cpp
There's a snowball's chance in hell that we're going to treat rational literals as fixed-point, so I think it's safe to remove `#pragma rational`.
> Remove #pragma rational.

- include/core/float.inc
- include/smx/smx-v1-opcodes.h
- tests/basic/float-math.sp
- tests/float.inc
- tests/runtests.py
- vm/AMBuilder
- vm/builtins.cpp
- vm/builtins.h
- vm/environment.cpp
- vm/environment.h
- vm/plugin-runtime.cpp
Currently, floating point functions in SourcePawn are optimized by hardcoding the native names SourceMod uses. The hack is not very rigorous. Nevertheless, it exists, and it's why spshell is able to use float ops despite not having the natives.
Let's finally promote at least some of the floating point library to builtin status. We'll probably see more of this in the future (since it's a nice way to prototype new opcodes too), so this patch introduces a "builtins" mechanism. The actual way things get bound is still tied to float native replacement.
Note that when using the new `<core/float>` include, the native names are different from SourceMod (`__float_sub` instead of `FloatSub`, for example). This again is in anticipation of having other special builtins for underlying features. …
> Fully support basic floating point operations in spshell.

- compiler/sc1.cpp
- compiler/sc6.cpp
- include/smx/smx-headers.h
- tools/smxtools/smxdasm/V1Types.cs
- tools/smxtools/smxviewer/MainWindow.cs
- vm/legacy-image.h
- vm/smx-v1-image.cpp
- vm/smx-v1-image.h
The codeversion field is a little too heavy weight and makes it difficult to support parallel
compiler branches. We ideally need a major/minor system or a feature flag set. In this patch
we opt for feature flags since they also make it easier to develop experimental features.
The version has been bumped to 13 for this patch.
Newer compilers will still emit codeversion=11 by default. The feature bits will still be present,
but set to zero. This is legal since the file format requires ignoring extra data between the
header and code blob, and indeed all old VMs follow this rule.
> Replace codeversion with feature flags.

- AMBuildScript
- compiler/AMBuilder
- exp/compiler/AMBuilder
- exp/tools/docparse/AMBuilder
- vm/AMBuilder
- vm/plugin-context.cpp
Small simplification to some AMBuild files (most of the code changes are dedents). Instead of iterating the archs in each script, iterate them in the root script instead.
> Don't iterate archs in buildscripts.

- compiler/sc1.cpp
- tests/compile-only/ok-anon-instansiation.sp
- tests/compile-only/ok-anon-instantiation.sp
This commit prevents anonymous instantiations in the form of `new Class()` from falling into declloc.
Fixes #162
> Add look-ahead for oldstyle decl

- compiler/sc1.cpp
Ancient bug - looks like it's a carryover from AMX Mod X.
The following script will misalign the HEA stack:
```
native void printnum(int n);
public main() {
while (true) {
for (int i = 1; i < 10; i++) {
char[] egg = new char[i];
if (i % 2 == 0) {
char[] yam = new char[i + 3];
break;
} else {
char[] yam = new char[i + 3];
continue;
}
}
}
}
```
> Fix a HEA leak when using break in nested scopes.

- compiler/sc2.cpp
Remove usage of `pow10`. This is documented as nonstandard GNU extension.
We already needed to have a shim for it on macOS, and using newer versions of Clang (tested v6) on Linux also fail to find it, even after explicitly including <math.h>. (I haven't tried newer GCC versions).
> Remove pow10 usage and shim.

- tools/verifier/verifier.cpp
- vm/control-flow.h
- vm/graph-builder.cpp
- vm/method-verifier.cpp
- vm/method-verifier.h
- vm/opcodes.cpp
This series of patches adds a few new verification steps. The first is that the stack must be _balanced_. The amount of stack space used must be equal across all incoming edges to a block. This has a few important implications:
1. The compiler is not allowed to leak stack space, which in a loop could easily yield a run-time error.
2. The amount of stack space used by a method must be _static_. 
3. The operand of any stack-affecting instruction can be assigned a constant offset from the base of the stack frame. (This will lead to big wins in the JIT).
The algorithm is simple: for each opcode, the stack balance is adjusted based on how much it adds or removes from the stack. When parsing each block, its initial stack balance is inherited from any predecessor, and it must be equal across all …
> Compute static memory requirements of methods.

- vm/control-flow.h
- vm/method-verifier.cpp
- vm/method-verifier.h
We can require a balanced HEA state in addition to STK. Heap allocations can be dynamic, which makes this a bit more complicated. We need to correctly interleave static and dynamic allocations, which requires a stack.
The really annoying problem, though, is that the compiler had a bug for 12 years where dynamic arrays were not freed on "break" statements inside loops. This messes up our analysis because the join point will see an empty heap state on one predecessor, and lingering dynamic variables in the other.
Two plugins in my corpus were affected by this bug. One of them still had the source code available, and I was able to work around it by detecting break statements and ignoring the balancing error. (I think it is okay, in this case, to pick a random predecessor's state to inherit, …
> Require a balanced heap state at join points.

- vm/method-info.cpp
- vm/method-info.h
- vm/method-verifier.cpp
- vm/method-verifier.h
- vm/x86/jit_x86.cpp
Now that methods are required to have a statically sized stack frame, we can check stack bounds in the method prologue. OP_STACK no longer needs any checks.
> Move stack checks to the function prologue.

- .travis.yml
Reverts alliedmodders/sourcepawn#225
The `incoming` branch of urho3d/emscripten-sdk was changed to be building a load of extra tools, and possibly lacking optimizations? First run of emcc was taking 6+ minutes and running out of memory. Switching to `master` which has now been updated to the EMSDK version we require has resolved this and everything seems to be working again.
> Reenable Emscripten CI

- tools/smxtools/smxdasm/File.cs
- tools/smxtools/smxviewer/MainWindow.cs
Just skip the invalid section instead of not opening the plugin at all. This allows us to at least have a look at the disassembly and valid sections even if some optional sections are malformed.
> SmxViewer: Don't abort when a section failed to parse

- tools/smxtools/smxdasm/File.cs
- tools/smxtools/smxdasm/Sections.cs
- tools/smxtools/smxdasm/V1Disassembler.cs
- tools/smxtools/smxdasm/V1Types.cs
- tools/smxtools/smxviewer/MainWindow.cs
When encountering a `call` while disassembling check if there is an entry for the called address in the ".publics" or ".dbg.symbols" sections. If the function is missing add it to a seperate list to be able to disassemble functions even while debug info is stripped.
The functions are added with a name like `sub_<addr>` to be unqiue.
> SmxViewer: Collect unknown functions while disassembling

- compiler/expression-parsing.cpp
- compiler/sc.h
- compiler/sc1.cpp
- compiler/sc2.cpp
- compiler/sc3.cpp
- compiler/sc4.cpp
- compiler/sc6.cpp
- compiler/sclist.cpp
- compiler/sctracker.cpp
- compiler/sp_symhash.cpp
Currently symbol names are stored as an inline buffer and a cached hash value. This is unnecessary
given we have a string pool, so let's use that instead. This also helps toward relaxing the restriction
on name lengths.
> Use atoms for symbol names.

- compiler/sc.h
- compiler/sc1.cpp
- compiler/sc2.cpp
- compiler/sc3.cpp
This is not used in SourceMod, and SMX does not have a library table.
> Remove some stuff from symbol.

- compiler/sc.h
- compiler/sc1.cpp
- compiler/sc2.cpp
- compiler/sc3.cpp
- compiler/sc6.cpp
- compiler/sclist.cpp
- compiler/sctracker.cpp
- compiler/sctracker.h
It's pretty gross to have this stuff in unions.
> Factor out function-specific fields from symbol.

- vm/smx-v1-image.cpp
If the .rtti.data section is present, but one of the other .rtti.* sections is missing, the VM still tried to validate the nullptr.
Fix a copy&paste typo in the native name error message as well.
> Fix crash on missing .rtti.* section

- vm/control-flow.cpp
Block::unlink() was never called, leading to cycles.
> Fix memory leak in ControlFlowGraph.

- vm/scripted-invoker.cpp
This is a useful hack I've had sitting in my queue for a while.
Copy the to-be-invoked function's debug name into the `ScriptedInvoker::Invoke` stack frame so it is always available in minidumps even without heap information.
This will hopefully make it easier to track down reproduction steps for plugin-related crashes.
> Copy function debug name onto stack for crash dumps

- compiler/sc2.cpp
lex() is pretty unreadable, it has duplicated code and weird state transitions, and it's too long. This patch breaks it up into separate methods that each perform a clear task.
The operator lookup code is now inlined into a switch statement (similar to how the v2 lexer works), removing a loop+strcmp over a sizable chunk of the token table. Compiling SourceMod's plugins looks about 5% faster with this change.
After this change, it will be much easier to implement a token map and remove the sc_token loop.
> Rewrite the lexer.

- compiler/sc1.cpp
- compiler/sctracker.cpp
- compiler/sctracker.h
Fixes building using gcc 8. Currently it fails due ```-Werror=class-memaccess```
> -Wclass-memaccess warns when objects of non-trivial class types are manipulated in potentially unsafe ways by raw memory functions such as ```memcpy```, or ```realloc```.
> The warning helps detect calls that bypass user-defined constructors or copy-assignment operators, corrupt virtual table pointers, data members of const-qualified types or references, or member pointers.
> The warning also detects calls that would bypass access controls to data members.
[Source](https://gcc.gnu.org/gcc-8/changes.html)
> Fix building GCC 8

- compiler/assembler.h
- compiler/codegen.h
- compiler/lexer.cpp
- compiler/lexer.h
- compiler/libpawnc.h
- compiler/optimizer.h
- compiler/parser.cpp
- compiler/sc.h
- compiler/sci18n.h
- compiler/sclist.h
- compiler/scvars.h
reduce_referrers tries to find unused symbols. During parsing, a simple
dependency tree is built, and this leads to a fixpoint algorithm
determining which symbols are transitively unused. Unfortunately, this
algorithm is ridiculously inefficient: it scans all global symbols
during each "sweep", and while processing each symbol, scans all global
symbols again if unused. Due to other considerations the algorithm is
essentially O(n*n*m).
This patch replaces it with a more efficient solution. This extends the
dependency graph to include backward and forward links, which means
reduce_referrers can use a simple topological sort. The new runtime is
closer to O(n). This is about a 10% improvement in compilation time.
The tricky aspect to this patch is that "symbol" is not pool-allocated
as it …
> Rewrite symbol pruning.

- compiler/lexer.cpp
- compiler/libpawnc.cpp
- compiler/libpawnc.h
- compiler/parser.cpp
- compiler/sci18n.cpp
- compiler/sci18n.h
- compiler/scvars.h
- tests/compile-only/ok-byte-order-mark.sp
This is a ~13% compile time improvement on SourceMod plugins.
Mysteriously, it wasn't enough to parse three times: the compiler
also pre-scans the entire text of source/include files to determine
if each uses UTF-8. This is particularly mysterious as the result
of pre-scanning for UTF-8 is that it will allow parsing more UTF-8
characters. Why bother scanning in the first place?
One reason is to remove the byte order mark (BOM), which this patch
retains by scanning the first three bytes. Otherwise, it seems this code
can be removed. It's possible upstream had more dependent logic and we
removed it long ago.
> Always parse as UTF-8.

- compiler/assembler.cpp
Code generation happens in three full passes over the assembly stream.
The first pass collects label addresses. The second pass generates code.
The final pass generates data. This is unnecessary; the first pass can
be eliminated via a lazy back-patch list. The last two passes can be
combined into one.
> Remove the three-pass codegen step.

- compiler/sclist.cpp
- compiler/sclist.h
The alias table is not large, but it searched every time a function is
called. Switching this to a hash table removes another dependency on
stringpair and improves compilation time by ~6%.
> Switch the alias table from a sorted linked list to a hash table.

- compiler/expressions.cpp
- compiler/sc.h
This is parsing state and has nothing to do with values. It was also
ridiculously complicated for the sole purpose of an obscure warning around
a specific type of self-assignment, a[y] = a[y]. Note that |a = a| does
have a warning, but only if |a| is scalar.
> Remove value::arrayidx.

- compiler/expressions.cpp
- compiler/messages.h
- compiler/parser.cpp
- tests/compile-only/fail-return-indeterminate-array.sp
- tests/compile-only/fail-return-indeterminate-array.txt
This bug was reported by KyleS.
> Fix a bug where returning an indeterminate array would assert.

- compiler/messages.h
- compiler/parser.cpp
- tests/compile-only/fail-duplicate-enum-struct-field.sp
- tests/compile-only/fail-duplicate-enum-struct-field.txt
- tests/compile-only/fail-enum-struct-reference.sp
- tests/compile-only/fail-enum-struct-reference.txt
This essentially guarantees that future struct implementations will have
pass-by-reference semantics. The alternative would be requiring a
reference token for enum structs, and then leaving the door open for
pass-by-value semantics later. However, there do not seem to be many use
cases for pass-by-value that could not be solved in other ways. And this
implementation matches how arrays and methodmaps are already used.
> Disallow reference tokens on enum struct parameters.

- compiler/parser.cpp
The compiler rewrites the definition address of all variables in the write phase. That second phase uses previous usage knowledge to exclude unused functions, making the binary smaller.
Struct variables are handled in a seperate `declstructvar` function which missed that write pass fixup.
Set the definition address of struct variables in the write pass es well.
Fixes #308
> Fix wrong debug codestart of struct variables

- tools/smxtools/smxdasm/Rtti.cs
- tools/smxtools/smxdasm/Sections.cs
- tools/smxtools/smxviewer/MainWindow.cs
The displayed line was looked up from the address of the end of the scope of the variable instead of where it's first declared.
`SmxDebugLocals::FindLocal` used the `.dbg.methods` before checking for null and didn't look for array variables correctly.
> SmxTools: Fix line and locals lookup of rtti symbols

- compiler/parser.cpp
- tests/compile-only/fail-ref-arg-with-array-type.sp
- tests/compile-only/fail-ref-arg-with-array-type.txt
> Disallow references on indeterminate array arguments.

- vm/environment.h
When a plugin is currently executing code while the profiler is being activated, the VM tried to leave a profiling scope it never entered.
`sm_rcon sm prof start vprof` would crash the server.
https://crash.limetech.org/lgolraffyt46
> Fix crash when enabling profiler

- compiler/errors.cpp
- compiler/lexer.cpp
- compiler/lexer.h
- compiler/parser.cpp
- tests/compile-only/fail-missing-semi-on-enum-struct.txt
- tests/compile-only/ok-enum-struct-to-any-array.sp
- tests/enum-structs/array-of-structs.sp
- tests/enum-structs/chained-method-call.sp
- tests/enum-structs/dynamic-arrays.sp
- tests/enum-structs/inline-arrays.sp
- tests/enum-structs/method-call.sp
- tests/enum-structs/methodmap-in-struct.sp
- tests/enum-structs/nested.sp
- tests/enum-structs/resolve-field-offsets.sp
- tests/enum-structs/simple.sp
- tests/enum-structs/sizeof-enum.sp
- tests/enum-structs/sizeof-type.sp
- tests/enum-structs/sizeof-var.sp
- tests/enum-structs/string-fields.sp
- tests/runtests.py
This patch tweaks the require_newline algorithm to allow for three
scenarios:
(1) A declaration where ONLY newlines are allowed to terminate a
statement. Enum structs now fall into this category.
(2) A declaration where semicolons OR newlines are allowed to terminate
a statement. Methodmaps, typesets fall into category. If a semicolon is
missing, requiring semicolons with a pragma will not error. This mode is
for compatibility, since the original semantics were a mistake
(methodmaps should be "newline", typesets should be "semicolon").
(3) A declaration where semicolons are required to terminate a
statement. If semicolons are not required with a #pragma, then the
missing semicolon is ignored and a newline is accepted.
Finally, this patch fixes a bug where token_pos_t did not track the …
> Fix issues related to line terminators on global declarations.

- compiler/expressions.cpp
- compiler/lexer.cpp
- compiler/lexer.h
- compiler/parser.cpp
- compiler/scvars.cpp
- compiler/scvars.h
- tests/compile-only/fail-empty-parenthetical.sp
- tests/compile-only/fail-empty-parenthetical.txt
This mechanism was an untyped stack for squirreling away data while the
compiler processed nested structures. This was gross even for a C
codebase: each individual item should have had its own stack, since then
if the stack is unbalanced, it is much clearer where the fault lies.
Even then the stack was used unnecessarily in many places. For example
sc_intest and sc_allowtags were trivially scoped.
Bug: issue #312
> Remove POPSTK_I/P.

- compiler/parser.cpp
KE_CONSTEXPR define was removed in this commit: https://github.com/alliedmodders/amtl/commit/7586906494fd1df46c468309798b5d3f49c95b39
> KE_CONSTEXPR define was removed

- AMBuildScript
Fix #323 
* Add `EnsureLibSmx` in the project-wide `AMBuildScript`'s option parser for the `exp` branch
> Fix exp libsmx dependency not being automatically satisfied

- AMBuildScript
Fix #325 
* Use libc++ if apple clang of version 10+ is detected
> Use libc++ instead of no-longer supported libstdc++ on XCode 10 and above

- compiler/parser.cpp
- tests/compile-only/ok-methodmap-decl-no-semi.sp
This was probably what was intended in https://github.com/alliedmodders/sourcepawn/pull/319.
> Make semicolons after methodmap declarations optional, even with #pragma semicolon.

- vm/environment.h
The crash fix in #316 didn't initialize the member variable, so it doesn't really fix the issue. It seems I just got tricked during testing with debug builds.
https://crash.limetech.org/R4777WANZDTG
> Fix uninitialized variable guarding profiling scopes

- .travis.yml
- AMBuildScript
- compiler/AMBuilder
- tools/travis-download-compiler.sh
- vm/AMBuilder
- vm/watchdog_timer.cpp
This ended up needing quite a lot of mangling:
* Moved us to the latest travis build image and using distro Clang 7.x
* Switched to the upstream emscripten SDK, now it has pre-build linux bins
* Bit of compiler flag cleanup that were getting duplicated after prior refactoring work
* Fixed an unrelated issue with setting arch flags on Windows
* Added a stub for prctl to fix linking issues
> Fix Travis Emscripten build

- vm/jit.h
- vm/runtime-helpers.cpp
- vm/runtime-helpers.h
- vm/x64/macro-assembler-x64.cpp
- vm/x64/macro-assembler-x64.h
- vm/x86/jit_x86.cpp
- vm/x86/macro-assembler-x86.h
When invoking C++ from JIT code, we need to construct an "exit frame"
so that FrameIterator can recover a stack trace. The normal way of
creating an exit frame is implicitly, via a call. The call pushes a
return address, and the new prologue configures the frame pointer and
stores it in the Environment.
Notably, this means there is a small inline helper function every time
we transition to C++. For performance-sensitive code, like native calls,
this is not ideal. Instead we create an "inline" exit frame. Instead of
calling, we derive the return address at compile-time, push it, and thus
avoid the call instructions.
This patch makes additional improves to the inline-exit path by also
eliding "leave" instructions. It also preserves ebp, which should
improve stack walking by Breakpad.
> Simplify inline exit frames.

- compiler/parser.cpp
- tests/warnings/unused-from-member-function.sp
Bug: issue #349
Test: warnings/unused-from-member-function.sp
> Fix warning when non-stock functions are used by stock functions.

- tools/smxtools/smxviewer/MainWindow.cs
The format string referenced the first argument twice.
> Fix casetbl case address disassembly

- compiler/expressions.cpp
- compiler/parser.cpp
- compiler/sc.h
- compiler/sctracker.cpp
- compiler/types.cpp
- compiler/types.h
The two-pass parser treats any unknown variable as a function, and if
those leak into expressions, it can lead to weird error messages.
Bug: issue #354
Test: manual test
> Improve type pretty-printing. Slightly.

- compiler/messages.h
- compiler/parser.cpp
- tests/compile-only/fail-enum-struct-const-field.sp
- tests/compile-only/fail-enum-struct-const-field.txt
Fixes #363 
Prevents enum struct fields from being `const`. I'm not sure we want to support const enum struct members, so if that is something we want I can refactor this, but I went straight for removal & error.
Added test
> Disqualifiy const from enum struct fields

- compiler/assembler.cpp
- compiler/codegen.cpp
- compiler/codegen.h
- compiler/expressions.cpp
- compiler/parser.cpp
- compiler/scvars.cpp
- compiler/scvars.h
For some reason, natives had a weird relationship with the assembler.
The code generator assigned an address based on a global counter, and
then the assembler was responsible for building the table in the same
order. (Similar nonsense exists with the staging counter, but we'll save
that for another day.)
Instead, emit sysreq instructions by name as we do for the call
instruction. This allows us to build the table during code generation,
simplifying another piece of the assembler pipeline.
Bug: N/A
Test: manual test
> Eliminate the native counter hack.

- compiler/expressions.cpp
Getting a non-zero result looks impossible. An array and non-array value
cannot flow into a binary operator, and this is prevented by various
checks. When the operator is not '=', arrays are entirely rejected.
Bug: N/A
Test: tests pass
> Remove dbltest().

- compiler/expressions.cpp
- tests/compile-only/fail-array-char-to-int-ref.sp
- tests/compile-only/fail-array-char-to-int-ref.txt
This can't be properly supported because there is no 8-bit char type. As
is, it performs an improper memory access.
Bug: N/A
Test: compile-only/fail-array-char-to-int-ref
> Forbid passing character slices to references.

- compiler/expressions.cpp
It is impossible to have an rvalue here.
Bug: N/A
Test: code coverage w/ test suite and forum corpus
> Remove dead code handling rvalues in callfunction().

- compiler/parse-expr.cpp
This is unreachable because enum structs have symbols.
> Remove dead code for sizeof().

- compiler/messages.h
- compiler/parser.cpp
- compiler/types.h
- tests/compile-only/fail-legacy-enum-structs.sp
- tests/compile-only/fail-legacy-enum-structs.txt
Bug: N/A
Test: compile-only/fail-legacy-enum-structs
> Warn when legacy enum structs are used.

- .travis.yml
- AMBuildScript
- compiler/AMBuilder
- compiler/parser.cpp
- exp/compiler/AMBuilder
- exp/tools/docparse/AMBuilder
- vm/AMBuilder
This removes a bunch of hand-rolled argument parsing code. Two options
have been removed: -^ and -\ which allowed switching the control
character, generally a poor idea for having shareable code.
> Switch to the AMTL argument parser.

- compiler/parser.cpp
Bug: fixes issue #396
Test: spcomp -o /does/not/exist.smx
> Fix double-free when a fatal error occurs during assembly.

- compiler/expressions.cpp
- compiler/expressions.h
- compiler/new-parser.cpp
- compiler/parse-node.h
- compiler/semantics.cpp
- tests/compile-only/ok-void-function-as-value.sp
The old parser could not determine whether a function call result was
used or not. To implement the warning, it would aggressively check
whether the inputs to an expression involved a function symbol, and mark
it as needed a return value. This mostly worked because check was copied
into the most common cases in the parser.
This broke in the new parser because functions identifiers are pipelined
rather than immediately evaluated. They always return a function symbol,
and the caller is responsible for evaluating it. This is different from
the old parser, where a function symbol immediately created a call
expression or a "function value" expression. As a result, the hack for
aggressively poking at potential function calls no longer works.
This can be resolved by using the AST. Each node must …
> Fix marking function return values.

- compiler/expressions.cpp
- tests/compile-only/ok-index-with-any-type.sp
Bug: issue #401
Test: compile-only/ok-index-with-any-type.sp
> Allow "any" type as an array index.

- compiler/semantics.cpp
- tests/compile-only/fail-assign-scalar-to-array.sp
- tests/compile-only/fail-assign-scalar-to-array.txt
I truly do not understand the condition that was supposed to prevent this. Possibly, the original author meant the last "&&" to be an "||". But even taking that into account, it looks bogus. I can't think of anything illegal it actually prevents, except maybe constant literals that are <= 0.
> Fix scalars being assignable to arrays.

- exp/compiler/parser/json-tools.cpp
- exp/compiler/parser/json-tools.h
- exp/tools/docparse/docparse.cpp
JsonRenderer constructor param was changed to a more generic out stream from std
To allow the ability to store serialized JSON into a buffer and used else other (in my case, ffi), instead of stdout.
Docparse output has been linted with jq
> exp::parser - generic json renderer outstream

- compiler/assembler.cpp
- compiler/code-generator.cpp
- compiler/emitter.cpp
- compiler/expressions.cpp
- compiler/lexer.cpp
- compiler/lexer.h
- compiler/name-resolution.cpp
- compiler/parser.cpp
- compiler/sc.h
- compiler/sclist.cpp
- compiler/sctracker.cpp
- compiler/sctracker.h
- compiler/semantics.cpp
- compiler/types.h
These fields are really annoying when debugging, I have to look up the bit assignments every time, and some of them are overlapped. This patch series moves everything but uREAD and uWRITTEN into dedicated fields.
> Refactor symbol::usage and symbol::flags.

- exp/compiler/source-manager.cpp
- exp/compiler/source-manager.h
Adds SourceManager::createFromBuffer to allow creation from a buffer instead of file path
In wasm targets, local file creation are not possible, this method allows the creation of RefPtr<SourceFile> from a buffer instead.
> exp::compiler::source-manager - added createFromBuffer method

- compiler/parser.cpp
- tests/compile-only/warn-switch-tag-mismatch.sp
- tests/compile-only/warn-switch-tag-mismatch.txt
Bug: issue #435
Test: compile-only/warn-switch-tag-mismatch
> Check switch cases for tag mismatches.

- exp/tools/docparse/docparse.cpp
Currently there is no way to distinguish between native methods and regular methods in methodmaps. This adds a new `kind` field like the one in functions that can be either `native` or `stock`.
> Add "kind" field to methods in docparse

- compiler/semantics.cpp
- tests/compile-only/warn-array-literal-mismatch.sp
- tests/compile-only/warn-array-literal-mismatch.txt
Array expressions would never get their tag set, which causes tag mismatches when the type of the array isn't an `int`.
Fixes #288
> Set tag on array expressions

- compiler/assembler.cpp
- compiler/code-generator.cpp
- compiler/expressions.cpp
- compiler/lexer.cpp
- compiler/lexer.h
- compiler/messages.h
- compiler/name-resolution.cpp
- compiler/new-parser.cpp
- compiler/new-parser.h
- compiler/parse-node.h
- compiler/parser.cpp
- compiler/sctracker.cpp
- compiler/sctracker.h
- compiler/semantics.cpp
- compiler/types.h
This patch series moves a bunch of top-level statement parsing code into the new AST-based parser. To preserve behavior, each statement is immediately resolved after being parsed. The major change here is that the parsing, name resolution, and evaluation now occurs in three distinct steps and is no longer intermingled.
This covers the easy global statement cases. The most difficult case is function statements, which cannot be moved until all non-global statements have been moved as well.
> Begin moving parser.cpp to an AST.

- compiler/code-generator.cpp
- compiler/lexer.cpp
- compiler/lexer.h
- compiler/new-parser.cpp
- compiler/parse-node.h
- compiler/parser.cpp
- compiler/pool-allocator.h
- compiler/sc.h
- compiler/scvars.cpp
- compiler/scvars.h
- compiler/semantics.cpp
Everything about string literal parsing is a mess, perhaps the worst offense is that the lexer injects the byte stream directly into the DATA section. It's hard to think of a bigger layering violation.
This patch series attempts to clean things up by:
1. Removing code around RAWMODE and unpacked string support which has no use cases and has been continually and incrementally broken for ages. (RAWMODE I'd be happy to bring back with a new syntax, like Python's r"blah").
2. Refactoring code to not lex directly into DATA.
3. Move literal queue usage from the parser into the code generator (for expressions).
> Clean up string literal messes.

- compiler/parser.cpp
- tests/compile-only/fail-argument-name-is-keyword.sp
- tests/compile-only/fail-argument-name-is-keyword.txt
Bug: fixes #458
Test: compile-only/fail-argument-name-is-keyword.sp
> Fix assert when using keywords as argument names.

- AMBuildScript
AMBuildScript:81: SyntaxWarning: "is" with a literal. Did you mean "=="?
have_gcc = cxx.family is 'gcc'
AMBuildScript:82: SyntaxWarning: "is" with a literal. Did you mean "=="?
have_clang = cxx.family is 'clang' or cxx.family is 'emscripten'
AMBuildScript:82: SyntaxWarning: "is" with a literal. Did you mean "=="?
have_clang = cxx.family is 'clang' or cxx.family is 'emscripten'
> Fix warnings in AMBuild script on newer Python versions.

- exp/tools/docparse/docparse.cpp
This PR implements a support writing parent type name. This can be used in docgen for displaying all exists method for methodmaps (such as `Handle.Close()` in `Database`).
Property name: `parent`.
> Add "parent" property for methodmaps

- compiler/lexer.cpp
- compiler/parser.cpp
- compiler/sc.h
- compiler/sp_symhash.cpp
- tests/compile-only/warn-report-right-file.inc
- tests/compile-only/warn-report-right-file.sp
- tests/compile-only/warn-report-right-file.txt
This could probably be used to report stuff like the location of a shadowed symbol instead of just the name.  Maybe other compiler messages could also use it.
> Fix up location tracking for symbols

- vm/x64/code-stubs-x64.cpp
Microsoft demands 32 bytes of shadow space on the stack before calling a function even if the function has less than 4 parameters.
> Fix calling fake natives on x64 Windows

- tools/checkout-deps.sh
- Checks for an active 'python'/'python3' command.
- Checks for an active pip installation in the detected Python installation, otherwise, it installs it via 'get-pip.py'
See: alliedmodders/ambuild#68
> Updated 'checkout-deps' to check for 'pip'/'pip3' prior to installing 'AMBuild'

- compiler/lexer.cpp
- compiler/parser.cpp
- tests/compile-only/fail-crash-on-redecl-function.sp
- tests/compile-only/fail-crash-on-redecl-function.txt
- tests/compile-only/fail-multi-character-sequence.sp
- tests/compile-only/fail-multi-character-sequence.txt
This also fixes a bug where if the compiler encountered an error while
parsing a global variable initializer, the error would be ignored if the
variable was unused.
Bug: issue #506
Test: tests/compile-only/fail-multi-character-sequence.sp
> Fix bad error messages on multi-character sequences.

- compiler/parser.cpp
- tests/compile-only/fail-old-any-decl.sp
- tests/compile-only/fail-old-any-decl.txt
Bug: issue #469
Test: tests/compile-only/fail-old-any-decl.sp
> Fix any: not triggering a newdecls warning.

- tests/testutil.py
spshell JIT detection failed due to an argparser bug. Fix running the test suite on Python 3 while we're at it.
> Fix tests not using JIT

- tools/smxtools/smxviewer/MainWindow.cs
The logic to find the index of the last field of the last enum-struct had a typo.
> SmxViewer: Fix display of last enum-struct's fields

- vm/smx-v1-image.cpp
According to the description, last_header_string (the nameoffs field of one of the sp_file_section_t structure) is an offset relative to header_strings_, instead of being an offset relative to the beginning of the buffer.
> Fix section header strings validation

- compiler/semantics.cpp
- tests/compile-only/ok-ternary-obj-types.sp
Bug: #536
Test: tests/compile-only/ok-ternary-obj-types.sp
`matchtag(some_methodmap, null_t)` works but `matchtag(null_t, some_methodmap)`.  Use `matchtag_commutative` instead so both `expr ? obj : null` and `expr ? null : obj` work.
> Fix ternary rejecting expr ? null : obj

- compiler/messages.h
- compiler/semantics.cpp
- tests/compile-only/fail-enum-struct-field-not-found.txt
- tests/compile-only/fail-undeclared-static-methodmap-call.sp
- tests/compile-only/fail-undeclared-static-methodmap-call.txt
Fixes https://github.com/alliedmodders/sourcemod/issues/1453
This patch just uses the name we looked up instead of the name from the (null) `field_` var.
Now errors with
```
SourcePawn Compiler 1.11
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2018 AlliedModders LLC 
test.sp(8) : error 105: cannot find method or property TestA.UndeclaredStaticFunc 
```
> Fix crash on undeclared static methodmap error

- .github/workflows/ci.yml
- AMBuildScript
Builds and tests on Linux, Windows and MacOS for x86 and x64.
The macOS builders don't support x86 builds anymore, so only test x64.
Build for arm and arm64 on Windows as well, but can't run the binaries yet.
> Start using Github Actions for CI

- compiler/new-parser.cpp
In Sourcemod 1.11 the following code fails to compile after moving enum parsing to new-parser.cpp in commit f598f1d22e9a596b70dd212ecf72d9655c965a9c
```
enum CheatType(+=1)
{
Cheat_HighPerfects = 0,
Cheat_Auto,
Cheat_JumpSpam
};
public void OnPluginStart() { }
```
Errors:
```
% ./compile.sh test.sp
Compiling test.sp...
SourcePawn Compiler 1.11.0.6625
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2018 AlliedModders LLC
test.sp(1) : error 001: expected token: "{", but found "("
test.sp(6) : error 010: invalid function or declaration
test.sp(3) : warning 203: symbol is never used: "Cheat_JumpSpam"
test.sp(3) : warning 203: symbol is never used: "Cheat_Auto"
test.sp(3) : warning 203: symbol is never used: "Cheat_HighPerfects"
```
> Fix enum increment/multiplier parsing

- compiler/lexer.cpp
- tests/compile-only/ok-char-literal-in-macro.sp
The lexer checks for a double quote before doing a pretty nugatory microoptimization. This check is incorrect, single quotes need to be fed into skipstring() as well. I've retained the optimization and simplified the code a bit.
I've also refactored this code a bit since it had way too much nesting, all to dance around needing manual free() calls.
> Fix single quote bug in preprocessor

- compiler/lexer.cpp
- tests/compile-only/include/extension.inc
- tests/compile-only/include/extension/file.inc
- tests/compile-only/ok-relative-includes.sp
This PR aims to solve https://github.com/alliedmodders/sourcepawn/issues/245 (Including files from withing sub directory with relative path is inconsistent/fails)
Motivation:
In larger plugins subdirectories are used to create structure in the project, however with the current handling of include paths it would make cross platform development and automation of multi platform CI/CD a pain.
Potential issues:
This change would be breaking for current projects developed on windows with a subdirectory structure. It would be relatively easy to fix for project maintainers by making the includes relative to the file that is including them.
Credits go to @impact123 for coming up with the proposed solution.
> Sync include behavior for subdirectories between windows and linux

- include/sp_vm_api.h
- vm/AMBuilder
- vm/api.cpp
- vm/debug-metadata.cpp
- vm/debug-metadata.h
- vm/environment.cpp
- vm/environment.h
- vm/jit.cpp
- vm/jit.h
- vm/jitdump.h
- vm/linking.cpp
- vm/linking.h
- vm/shell.cpp
- vm/x64/code-stubs-x64.cpp
- vm/x86/code-stubs-x86.cpp
Implemented here is the [original perf JIT format](https://github.com/torvalds/linux/blob/614cb5894306cfa2c7d9b6168182876ff5948735/tools/perf/Documentation/jit-interface.txt) which is widely supported but only supports simple name mapping, and the [newer "jitdump" format](https://github.com/torvalds/linux/blob/614cb5894306cfa2c7d9b6168182876ff5948735/tools/perf/Documentation/jitdump-specification.txt) which additionally supports embedding the machine code and source mapping information (along with a bunch of other things we don't currently have in the JIT).
Example usage:
```
fib(42) = 267914296
[ perf record: Woken up 9 times to write data ]
[ perf record: Captured and wrote 2.124 MB perf.data (6339 samples) ]
99.97%     0.00%  spshell  libc-2.29.so                [.] __libc_start_main
| …
```
> Implement perf JIT reporting APIs

- vm/debug-metadata.cpp
64-bit number format specifiers are platform dependant, and the older Clang version used by SM can't figure out the ternary here at compile time so throws a warning.
> Use AMTL defines for perf jit log printing

- compiler/messages.h
- compiler/semantics.cpp
- tests/compile-only/fail-sizeof-before-fully-parsed.sp
- tests/compile-only/fail-sizeof-before-fully-parsed.txt
This error will go away if we can remove the two-pass parsing scheme.
Bug: #559
> Error if using sizeof() without full parsing information.

- compiler/expressions.cpp
- compiler/expressions.h
- compiler/sctracker.cpp
- compiler/sctracker.h
- tests/compile-only/fail-bad-function-casts.sp
- tests/compile-only/fail-bad-function-casts.txt
- tests/compile-only/fail-bad-signature-cast.sp
- tests/compile-only/fail-bad-signature-cast.txt
- tests/compile-only/ok-signature-cast-type-pun.sp
This fixes a few bugs in typedef/function signature checks.
First, typedef-to-typedef comparisons are now valid. They previously
would always fail, due to the type checker requiring the type to be
backed by a function symbol.
Second, methodmap checks are now bidirectional. Eg, Handle casts to
DataPack and DataPack casts to Handle. This is a convenience cludge that
is commonly used, we can't easily break it, so now it is codified.
Third, arrays only implicitly cast if tags are identical. This is not
ideal, but it suffices until better rules can be written. For now it
prevents char[] casting to something with integer width.
Finally, a callback using a non-"any" type cannot be passed to a callback
using the "any" type. This prevents illegal implicit casts that we can't
yet do runtime checks …
> Fix inconsistencies with function signature type checks.

- AMBuildScript
Error message:
```
In file included from /home/karol/Programs/Repos/sourcepawn/vm/plugin-runtime.h:18,
from /home/karol/Programs/Repos/sourcepawn/vm/control-flow.h:23,
from /home/karol/Programs/Repos/sourcepawn/vm/control-flow.cpp:14:
/home/karol/Programs/Repos/sourcepawn/third_party/amtl/amtl/am-string.h: In function ‘std::unique_ptr<char []> ke::detail::SprintfArgsImpl.constprop(size_t*, const char*, va_list)’:
/home/karol/Programs/Repos/sourcepawn/third_party/amtl/amtl/am-string.h:89:1: error: ‘block’ directive output truncated writing 5 bytes into a region of size 2 [-Werror=format-truncation=]
89 | SprintfArgsImpl(size_t* out_len, const char* fmt, va_list ap)
```
The same fix has been applied to [alliedmodders/amtl](https://github.com/alliedmodders/amtl).
> Fix building using GCC

- vm/environment.cpp
- vm/interpreter.cpp
- vm/jit.cpp
- vm/legacy-image.h
- vm/method-info.h
- vm/method-verifier.cpp
- vm/smx-v1-image.cpp
- vm/smx-v1-image.h
This validates that all method calls have an associated RTTI entry, if
the RTTI table is present. Signature validation will come in 1.12.
No opcode depends on RTTI yet, so the compiler does not yet enforce
RTTI tables to be emitted. This is to allow 1.11-compiled plugins to run
on SourceMod 1.10.
Bug: issue #580
Bug: alliedmodders/sourcemod #1525
> Require RTTI-enabled plugins to have valid RTTI entries.

- compiler/name-resolution.cpp
- compiler/parse-node.h
- tests/compile-only/fail-assign-is-not-usage.sp
- tests/compile-only/fail-assign-is-not-usage.txt
A hack in the new parser caused assigned-but-not-used symbols to be
counted as used. Add a hack to this hack to differentiate lval from rval
assignment.
This will go away if we can remove the two-pass parser.
Bug: #545
> Fix assignment counting as "read" usage.

- compiler/assembler.cpp
- compiler/emitter.cpp
- compiler/parser.cpp
- compiler/sctracker.cpp
- compiler/scvars.cpp
- compiler/scvars.h
- tests/basic/huge-array-validates.sp
This eliminates a common use case for #pragma dynamic.
Bug: #501
Test: new runtime test
> Adjust memory based on inferred maximum stack size.

- compiler/lexer.cpp
- compiler/parser.cpp
- tests/basic/file-const-include.inc
- tests/basic/file-const.out
- tests/basic/file-const.sp
This PR implements a feature requested in [#182 (Compiler define \_\_FILE\_\_)](https://github.com/alliedmodders/sourcepawn/issues/182)
It adds two new macros that can be used for debugging purposes, like `__LINE__`:
* ``__FILE_PATH__`` - A string containing the full path the the document where it is used in.
* ``__FILE_NAME__`` - A string containing just the name of the current file without a path.
I used ``__BINARY_PATH__`` and ``__BINARY_NAME__`` as examples on how to implement these definitions.
> added __FILE_PATH__ and __FILE_NAME__ definitions

- compiler/lexer.cpp
- tests/compile-only/ok-macro-repeat-expansion.sp
This small refactoring allows us to easily fix remaining expansion bugs
while retaining all of our previous fixes.
Bug: #597
> Refactor macro expansion to be recursive.

- compiler/parser.cpp
Obviously this is the exact opposite of where we're trying to go with
the parser, but unfortunately it's the only simple way to fix a large
class of bugs.
The first pass of the compiler is designed to collect declarations and
usage information. Any errors are thrown away. The second pass then uses
the first pass to do proper error checking.
In the old model of semantics-as-you-parse, this sort of worked because
the compiler tried very hard to analyze everything in the first pass,
even if the analysis was bogus. In the new parser, it doesn't work as
well, because the analysis early-aborts in the first pass. This can
leave critical things missing. For example, we might skip checking a
function call or user operator, because we don't have type info. The
function then gets omitted in the …
> Add another parsing phase.

- tools/run_corpus.py
When making major changes to the compiler, we usually test them against
a saved copy of all plugins on the forums. Add a script to help automate
this.
Use `--remove-good` to reduce a corpus to only breaking plugins. This
helps narrow down a worklist.
Use `--remove-bad` to reduce a corpus to only working plugins. This
helps weed out known-bad plugins on a good compiler.
Use `--diagnose` to interactively choose whether to remove or keep a
non-working plugin.
Note that about half of all plugins in the current corpus will fail even
on a good compiler. We do not download includes or zip files so we'll
often miss dependencies. Still, this has been a pretty effective method
and gives us a test base of around 9,000 source files.
> Add a tool for testing a plugin corpus.

- compiler/parser.cpp
This is a completely unused feature to allow scripted destructors of
tags. We do not want to carry this forward in the current type system.
> Remove operator ~.

- tests/basic/restore-frame.out
- tests/basic/restore-frame.sp
- vm/plugin-context.cpp
This has always been a bug, but its more susceptible to hit thanks to
the new exception handling code. It requires two plugin stacks with C++
in between. If the inner stack returns an error, FRM won't be restored,
because popAmxFrame was never called.
Bug: issue #607
Test: restore-frame.sp
> Fix FRM not being restored on error.

- tests/basic/restore-frame.out
- vm/interpreter.cpp
- vm/pcode-reader.h
The interpreter should be using the "beginning of instruction" location,
not "end of instruction".
> Fix line numbers in stack traces in the interpreter.

- compiler/assembler.cpp
- compiler/code-generator.cpp
- compiler/emitter.cpp
- compiler/parse-node.h
- tests/compile-only/ok-balanced-ternary-array.sp
- tools/run_corpus.py
- vm/control-flow.h
- vm/environment.cpp
- vm/method-verifier.cpp
- vm/method-verifier.h
- vm/plugin-runtime.cpp
I discovered that the verify-after-compilation change wasn't actually doing anything, and fixed that. This led to the discovery of a verification bug from an uninitialized variable, that lucky, was extremely rare to manifest.
This led to the discovery of another bug from a [single plugin](https://forums.alliedmods.net/showthread.php?p=2684071) involving ternary operators. Fixing this in the compiler led to verification failures, which led to the discovery of two more bugs. First, the verifier did not track heap allocations versus "heap tracker" state properly. Second, the verifier did not track entry vs exit state separately, which makes it impossible to properly verify backedges.
All of this has been fixed in this patch series. I tested by building the corpus with 1.9 and 1.10, and then …
> Fix a quintet of related bugs.

- vm/graph-builder.cpp
This prevents GraphBuilder from scanning behind the end of the
instruction stream.
> Fix crash when function is missing an exit instruction.

- compiler/amx.h
- compiler/array-helpers.cpp
- compiler/assembler.cpp
- compiler/errors.cpp
- compiler/errors.h
- compiler/expressions.cpp
- compiler/expressions.h
- compiler/lexer.cpp
- compiler/lexer.h
- compiler/main.cpp
- compiler/name-resolution.cpp
- compiler/parse-node.h
- compiler/parser.cpp
- compiler/sc.h
- compiler/sctracker.cpp
- compiler/sctracker.h
- compiler/scvars.cpp
- compiler/semantics.cpp
- compiler/semantics.h
- compiler/symbols.cpp
- compiler/symbols.h
- compiler/types.cpp
- tests/compile-only/fail-method-name-too-long.sp
- tests/compile-only/fail-method-name-too-long.txt
This is vestigial gunk from when spcomp was C. There is no reason to
have hardcoded identifier lengths anywhere, and no reason to use C-style
string buffers.
This change ports almost all name info to sp::Atom. Atom is a wrapper
around std::string, except only one Atom is ever allocated for a given
string. We aggressively Atom-ize symbols during lexing, since any symbol
will wind up needing an atom anyway. This allows for cheap comparisons
during name lookup, since we can test with pointer identity.
This change also adds a new C++ (eg, non-printf/va_list) based reporting
mechanism. The intent here is to address the fact that error() is unsafe
because the C++ compiler can't check printf-formatting when the format
string is not constant. The new mechanism is backward compatible with
existing …
> Remove NAMEMAX defines.

- compiler/expressions.cpp
- compiler/expressions.h
- compiler/lexer.cpp
- compiler/messages.h
- compiler/name-resolution.cpp
- compiler/parse-node.h
- compiler/parser.cpp
- compiler/parser.h
- compiler/sc.h
- compiler/sctracker.cpp
- compiler/sctracker.h
- compiler/semantics.cpp
- compiler/symbols.cpp
These are some small cleanups, most importantly we've chosen a middle ground on enum feature removal. The +=1 and <<=1 cases have been pattern-matched (with a warning). Other values or operators will no longer work.
> Assorted cleanup, enum changes.

- tools/corpus/manifest.yaml
for json it exists [this include](https://github.com/clugg/sm-json/tree/master/addons/sourcemod/scripting/include), but it's not compatible since RIPExt use the same name "json.inc".
> Add some general includes files

- compiler/messages.h
- compiler/semantics.cpp
- tests/compile-only/fail-warn-dup-pstruct-arg.sp
- tests/compile-only/fail-warn-dup-pstruct-arg.txt
This now emits a warning instead of an error.
Test: fail-warn-dup-pstruct-arg.sp
> Allow pstruct args to be specified twice.

- compiler/lexer.cpp
- compiler/messages.h
- compiler/parser.cpp
This was never intended for public use. In the 1.11 parser it's too
difficult to separate from internal uses, and it causes assertion
failures.
> Deprecate #file.

- compiler/semantics.cpp
This makes it invalid to view_as to a different signature type. In
fact, view_as should *never* be used on functions. This is the first
step in battening down the hatches.
> Ensure function signatures are checked when performing casts.

- compiler/semantics.cpp
- tests/compile-only/ok-assign-int-to-arraychar.sp
Allow assigning an integer to an iARRAYCHAR.
Test: ok-assign-int-to-arraychar.sp
> Fix erroneous string assignment check.

- compiler/new-parser.cpp
- compiler/new-parser.h
- compiler/parser.cpp
- compiler/semantics.cpp
Although we now allow enum names as sizes again, this feature is getting
restricted to only work on array declarations. In any other context it
will error.
This does break a handful of plugins, and those plugins are often doing
something erroneous (like "return Action"). That is the intent behind
this change: it's very difficult to distinguish between valid uses and
typos. Other uses appearing valid actually have off-by-one errors.
> Restrict when enum names can be used as a size value.

- compiler/lexer.cpp
- compiler/lexer.h
- compiler/parser.cpp
- compiler/parser.h
- compiler/types.cpp
There is a lot of unnecessary duplication in the lexer API, both in ways
to match tokens and in structures used. This eliminates a bunch of it.
> Simplify the lexer API.

- compiler/errors.cpp
- compiler/lexer.cpp
- compiler/lexer.h
- compiler/messages.h
- compiler/parser.cpp
- tests/compile-only/fail-non-toplevel-include.sp
- tests/compile-only/fail-non-toplevel-include.txt
- tests/compile-only/ok-include-malformed-path.sp
This is a huge hack, but it will make it much easier to properly clean
up the implementation of scopes. The problem is that #include statements
can appear anywhere, eg:
public void
#include "blah.sp"
() {}
In the current system, static variables are globals that are tied to a
specific file. This requires attaching a file indicator to every name
lookup. It would be much cleaner to place statics into a dedicated
scope.
In the above example, "blah.sp" introduces a new static scope while in
the middle of parsing a function. This is extremely difficult to deal
with and exposes a bunch of crazy edge cases.
The effect of this change is that #include is now legal ONLY as a
top-level statement. It acts much like a declaration now. Due to the
lexer being very tricky, this works by injecting …
> Parse include directives as statements.

- compiler/array-helpers.cpp
- compiler/compile-context.cpp
- compiler/compile-context.h
- compiler/errors.cpp
- compiler/expressions.cpp
- compiler/expressions.h
- compiler/lexer.cpp
- compiler/lexer.h
- compiler/main.cpp
- compiler/name-resolution.cpp
- compiler/parser.cpp
- compiler/parser.h
- compiler/semantics.cpp
- compiler/symbols.h
- compiler/types.cpp
- compiler/types.h
- vm/debug-metadata.cpp
All lexer state is now encapsulated in a Lexer class.
> Eliminate static/global variables from lexer.cpp.

- compiler/assembler.cpp
- compiler/assembler.h
- compiler/code-generator.cpp
- compiler/compile-context.h
- compiler/compile-options.h
- compiler/emitter.cpp
- compiler/emitter.h
- compiler/errors.cpp
- compiler/lexer.cpp
- compiler/lexer.h
- compiler/main.cpp
- compiler/name-resolution.cpp
- compiler/parse-node.h
- compiler/parser.cpp
- compiler/scvars.cpp
- compiler/scvars.h
- compiler/semantics.cpp
These get moved into classes attached to CompileContext and friends.
The "listing" option is now removed, since we've tightly integrated the
preprocessor into the parser.
The "debug" option is now removed. Debug info is unconditionally
emitted.
> Remove a bunch of global variables.

- compiler/array-helpers.cpp
- compiler/assembler.cpp
- compiler/assembler.h
- compiler/ast-types.h
- compiler/code-generator.cpp
- compiler/code-generator.h
- compiler/main.cpp
- compiler/name-resolution.cpp
- compiler/parse-node.h
- compiler/parser.cpp
- compiler/semantics.cpp
This moves codegen out of the AST itself and into a separate generator
class, which manually walks the AST. The primary reason is to improve
encapsulation. There are many nodes that don't emit any code and don't
neatly slot into the previous design. The new design makes it easier to
have separate code generators. It also makes it easier to remove the
text-based emitter, since attaching all the emitter code to input
variables would be really cumbersome.
Currently the generator uses a big switch statement to avoid the cost of
two virtual dispatches.
A similar refactoring for SemaContext will likely happen as well.
> Invert the code generator's AST walk.

- compiler/assembler.cpp
- compiler/code-generator.cpp
- compiler/compile-context.h
- compiler/errors.cpp
- compiler/main.cpp
- compiler/parse-node.h
- compiler/sc.h
- compiler/semantics.cpp
- compiler/symbols.cpp
- compiler/symbols.h
This was always a hack in the multi-parse compiler, but now, we can do
it properly. The live set is "all public functions" and from there we
calculate a reachability graph and mark what's live.
Unlike the old system, we do not bother changing read/written flags. We
use a new bit since that's easier to do when statics are split into
their own scope.
Now that liveness works correctly, the new compiler will no longer emit
code for unused functions. This should even function better than 1.10/1.11.
> Properly implement liveness analysis

- compiler/assembler.cpp
- compiler/code-generator.cpp
- compiler/code-generator.h
- compiler/parse-node.h
- compiler/parser.cpp
- compiler/sctracker.h
- compiler/semantics.cpp
- compiler/semantics.h
- include/smx/smx-headers.h
- include/smx/smx-v1-opcodes.h
- tests/compile-only/ok-heap-and-ternary-operator.sp
- vm/control-flow.cpp
- vm/control-flow.h
- vm/interpreter.cpp
- vm/interpreter.h
- vm/method-verifier.cpp
- vm/method-verifier.h
- vm/pcode-reader.h
- vm/pcode-visitor.h
- vm/plugin-context.cpp
- vm/plugin-context.h
- vm/smx-v1-image.cpp
- vm/x86/jit_x86.cpp
- vm/x86/jit_x86.h
Since the AMX Mod X days we've dealt with heap allocations by trying to
precisely free them, similar to stack opcodes. This gets complicated by
the ternary operator which could have different allocations on each
side. It's further complicated by the method verifier, not to mention
nuances in evaluation ordering.
This patch throws away the entire concept of the "heap tracker". Heap
allocations are no longer precisely tracked, and the TRACKER opcodes are
banished from new binaries.
The new scheme is to save and restore the heap pointer via two new
codes: OP_HEAP_SAVE and OP_HEAP_RESTORE. These opcodes are emitted with
a much simpler granularity than the old tracker logic.
If a node requires heap allocations, we mark the node, and then set a
"pending allocation" bit. The nearest block …
> Rewrite heap tracking.

- compiler/name-resolution.cpp
- tests/compile-only/fail-define-public-twice.sp
- tests/compile-only/fail-define-public-twice.txt
Bug: issue #694
Test: fail-define-public-twice
> Don't allow defining the same public function twice.

- compiler/parser.cpp
- tests/compile-only/fail-issue701.sp
- tests/compile-only/fail-issue701.txt
Not sure if this should `continue` or `return` or if it makes a difference.
> Fix parsing of bad arguments (issue #701)

- compiler/assembler.cpp
- include/smx/smx-typeinfo.h
- tools/verifier/verifier.cpp
- tools/verifier/verify.py
- vm/AMBuilder
- vm/legacy-image.h
- vm/rtti.cpp
- vm/rtti.h
- vm/shell.cpp
- vm/smx-v1-image.cpp
- vm/smx-v1-image.h
This loads and validates all available `rtti.*` sections in the binary.
The new `.dbg.*` sections are only validated if the line debugger was enabled using `ISourcePawnEnvironment::EnableDebugBreak()` which isn't called in SourceMod yet.
The legacy `.dbg.symbols` section isn't parsed (yet?).
It's the first step to expose a symbol access API in the VM to implement an useful plugin debugger (ref #539).
> Implement RTTI parsing and validation in the VM

- compiler/lexer.cpp
- compiler/lexer.h
- compiler/sc.h
We can remove an arbitrary hardcoded limit, a fatal error path, and
simplify some data structures at the same time.
> Remove preprocessor level limits.

- compiler/assembler.cpp
- compiler/assembler.h
- compiler/compile-context.h
- compiler/errors.cpp
- compiler/errors.h
- compiler/lexer.cpp
- compiler/main.cpp
- compiler/messages.h
- compiler/parser.cpp
- tests/compile-only/fail-funcenum.txt
- tests/compile-only/fail-functag.txt
setjmp and longjmp can be used as an old-school exception handling
method in C programs. In C++ they're rarely used since they do not
trigger destructors.
Removing these calls makes spcomp more embeddable. We can also take the
opportunity to clean up one of the weirder paths still remaining in the
compiler: fatal errors. These abort the compiler immediately. It's a
little tricky to mimic this without longjmp, and we cannot use C++
exceptions in our code. It's also tricky to propagate fatal errors out
of the lexer, since it can be called from pretty much anywhere.
Instead, we just remove the concept of a fatal error. The only scenario
it really helps with is when we're overwhelmed with errors, and we can
sort of retain this by periodically checking if we should stop parsing.
> Remove setjmp/longjmp.

- AMBuildScript
- compiler/AMBuilder
- configure.py
- libsmx/AMBuilder
- tests/runtests.py
- tools/verifier/verifier.cpp
- tools/yapf-style
- vm/AMBuilder
- vm/api.h
- vm/builtins.cpp
- vm/code-allocator.h
- vm/debug-metadata.cpp
- vm/debug-metadata.h
- vm/dll_exports.cpp
- vm/jit.h
- vm/plugin-runtime.h
- vm/pool-allocator.h
- vm/smx-v1-image.cpp
- vm/smx-v1-image.h
- vm/stack-frames.h
- vm/x64/macro-assembler-x64.h
- vm/x86/assembler-x86.h
- vm/x86/jit_x86.h
- vm/x86/macro-assembler-x86.h
It's time to start treating the SourcePawn tree as one homogenous
component, rather than separate mini-libraries. This step of the
refactoring process applies only to the build scripts.
The compiler and VM are now built as one component. They stay in
separate folders for organization, although, we will begin refactoring
that organization in the not too distant future.
Together with zlib and amtl, we produce a libsourcepawn archive. This is
used to create libsourcepawn.so (which is used by SourceMod).
Local tools (spcomp, spshell, and verifier) build using the archive.
This has the nice side effect of generally simplifying our build
scripts.
Support for building exp/* is now removed. Docgen will be re-added via
spcomp in a later patch.
> Build a big ol' binary.

- compiler/name-resolution.cpp
- tests/compile-only/fail-initialized-var-is-unused.sp
- tests/compile-only/fail-initialized-var-is-unused.txt
Bug: issue #713
Test: fail-initialized-var-is-unused
> Don't mark lvalue initializers as read.

- compiler/lexer.cpp
Reverts alliedmodders/sourcepawn#730
Breakage on corpus, with patterns like:
#pragma newdecls required;
> Revert "Exact match check for #pragma newdecls values"

- compiler/array-helpers.cpp
- compiler/code-generator.cpp
- compiler/code-generator.h
- compiler/compile-context.cpp
- compiler/compile-context.h
- compiler/data-queue.cpp
- compiler/data-queue.h
- compiler/main.cpp
- compiler/parse-node.cpp
- compiler/parse-node.h
- compiler/sc.h
- compiler/semantics.cpp
- compiler/semantics.h
- compiler/source-file.cpp
- compiler/source-file.h
- compiler/stl/stl-allocator.h
- compiler/stl/stl-forward-list.h
- compiler/stl/stl-string.h
- compiler/stl/stl-unordered-map.h
- compiler/stl/stl-unordered-set.h
- compiler/stl/stl-vector.h
- compiler/symbols.h
- compiler/types.cpp
- compiler/types.h
This isn't perfect - overriding malloc/free would be better. But that's difficult and platform-specific, and probably would run into conflicts in embedding. So this is a reasonable stop-gap.
> Track big allocations that skip PoolAllocator.

- AMBuildScript
This patch should fix some redefinitions we were seeing in unrelated areas upstream in SourceMod by setting these flags on the binary and not cxx, which should only be used directly by top-level scripts.
> Fix top-level cxx polution

- compiler/stl/stl-allocator.h
This should fix some builds, as the stl allocator requires itself to be able to be rebound to other types and the previous definition of rebound isn't similar to other stl allocator implementations. 
This could potentially be fixed by
```c++
template <typename U>
using other = StlAllocator<U>;
```
But it's better to walk the beaten path here
> Edit rebind method for StlAllocator::other

- compiler/parser.cpp
- compiler/stl/stl-allocator.h
Our Linux buildbot is very old (Debian 7) and uses libstdc++ 4.9. Modern clang has a little trouble with it.
> Fix build on ancient STL.

- compiler/parse-node.h
- compiler/semantics.cpp
- tests/compile-only/fail-expression-has-no-effect.sp
- tests/compile-only/fail-expression-has-no-effect.txt
This also moves side effect testing into a single function, to eliminate
another virtual call.
Bug: issue #749
> Fix missing "expression has no side effect" warnings.

- compiler/semantics.cpp
- tests/regressions/fail-error-reporting-pos.sp
- tests/regressions/fail-error-reporting-pos.txt
- tests/runtests.py
Bug: issue #786
Test: regressions/fail-error-reporting-pos.sp
Also modifies `runtests.py` to allow passing `type` through from the
test file into the manifest.
> Fix wrong line reporting for errors (issue #786)

- compiler/lexer.cpp
- tests/regressions/ok-peek-same-line-lex.inc
- tests/regressions/ok-peek-same-line-lex.sp
Fix peek_same_line when the next token is in a different file, but happens to have the same line number.
> Fix peek_same_line

- compiler/symbols.cpp
- tests/compile-only/ok-argument-shadows-function.sp
This mimics an allowance made in the 1.10 compiler.
Bug: issue #791
> Allow argument names to shadow global functions.

- compiler/name-resolution.cpp
- tests/compile-only/fail-string-assigned-to-const-char.sp
- tests/compile-only/fail-string-assigned-to-const-char.txt
> Fix missing error message when const decl fails to evaluate.

- compiler/messages.h
- compiler/semantics.cpp
- tests/compile-only/fail-member-function-missing-call.sp
- tests/compile-only/fail-member-function-missing-call.txt
> Error when missing parens on member function calls.

- compiler/code-generator.cpp
- compiler/code-generator.h
- compiler/name-resolution.cpp
- compiler/parse-node.cpp
- compiler/parse-node.h
- compiler/parser.cpp
- compiler/parser.h
- compiler/semantics.cpp
- compiler/semantics.h
- compiler/symbols.h
- compiler/types.h
The thinking behind the split was that we'd have a base class for
function expressions versus function statements. But it's too
cumbersome and wasteful.
The remaining grossness is that Decl::name is decorated, which
complicates code that only cares about the undecorated name. For now
I've resolved this by holding the undecorated name separately, but there
may be lingering error messages and stuff that uses the wrong one.
> Merge FunctionInfo and FunctionDecl.

- compiler/ast-types.h
- compiler/code-generator.cpp
- compiler/name-resolution.cpp
- compiler/parse-node.h
- compiler/parser.cpp
- compiler/semantics.cpp
- compiler/semantics.h
CallExpr wasn't iterable because it stored its arguments in too many
places. This reduces it down to one list.
We also switch DefaultArgExpr to a parse-time node, and introduce
NamedArgExpr to eliminate more one-off weird structs.
> Streamline CallExpr and add iteration support.

- compiler/assembler.cpp
The `* 4` of the last dimension appears to be left over after some prior refactoring and is not needed anymore.
> Fix string array dimensions in rtti

- compiler/ast-types.h
- compiler/code-generator.cpp
- compiler/main.cpp
- compiler/name-resolution.cpp
- compiler/parse-node.cpp
- compiler/parse-node.h
- compiler/parser.cpp
- compiler/semantics.cpp
Having Exprs and Stmts in the same list is just an opportunity for
mistakes. This patch splits it into two separate lists.
> Split up AstKind.

- compiler/parser.cpp
- tests/compile-only/fail-static-assert-message.sp
- tests/compile-only/fail-static-assert-message.txt
- tests/compile-only/fail-static-assert-no-message.sp
- tests/compile-only/fail-static-assert-no-message.txt
- tests/compile-only/ok-static-assert-enum-value.sp
Bug: issue #823
Tests: compile-only/fail-static-assert-message.sp
compile-only/fail-static-assert-no-message.sp
compile-only/ok-static-assert-enum-value.sp
> Allow static_assert as a statement.

- compiler/AMBuilder
- compiler/compile-context.cpp
- compiler/compile-context.h
- compiler/errors.cpp
- compiler/lexer.cpp
- compiler/lexer.h
- compiler/main.cpp
- compiler/messages.h
- compiler/parser.cpp
- compiler/source-file.cpp
- compiler/source-file.h
- compiler/source-location.h
- compiler/source-manager.cpp
- compiler/source-manager.h
- exp/compiler/source-manager.h
This consolidates a bunch of per-file lexer state into a single object. It also introduces a SourceManager class, which opens and tracks source files. These are both concepts from the experimental compiler that are necessary for a long-overdue correction to the lexer, which is that it scans on a line-by-line basis rather than by character.
> Clean up Lexer state a bit.

- compiler/messages.h
- compiler/semantics.cpp
- tests/compile-only/warn-function-name-in-test.sp
- tests/compile-only/warn-function-name-in-test.txt
> Add a warning when function names are used as test conditions.

- compiler/main.cpp
- compiler/messages.h
- compiler/semantics.cpp
- tests/compile-only/fail-call-with-invalid-address.sp
- tests/compile-only/fail-call-with-invalid-address.txt
This was due to a missing error report causing us to generate code off
an invalid AST. Probably the AST should include placeholders to prevent
this. For now, add some guardrails against this kind of problem.
Bug: issue #750
> Fix crash when calling invalid address.

- compiler/compile-context.h
- compiler/main.cpp
If an output name is specified, it's now used exactly as given.  Also clean up
some file name handling that was doing nothing now that .asm/.lst output is gone.
> Don't force the output file to have an .smx extension.

- compiler/array-helpers.cpp
- compiler/array-helpers.h
- compiler/assembler.cpp
- compiler/code-generator.cpp
- compiler/code-generator.h
- compiler/expressions.h
- compiler/messages.h
- compiler/name-resolution.cpp
- compiler/parse-node.cpp
- compiler/parse-node.h
- compiler/parser.cpp
- compiler/pool-allocator.h
- compiler/sc.h
- compiler/semantics.cpp
- compiler/semantics.h
- compiler/symbols.cpp
- compiler/symbols.h
- compiler/type-checker.cpp
- compiler/types.h
- tests/compile-only/fail-pass-arraycell-to-refarray.sp
- tests/compile-only/fail-pass-arraycell-to-refarray.txt
- tests/compile-only/fail-return-indeterminate-array.txt
- tools/corpus/corpus_skip.list
There's a bunch of stuff in this series, removing more crap from the pre-AST compiler. But the biggie is removing symbol::child. We no longer create a symbol for each dimension of an array. This simplifies a lot of code, and fixes some long-standing semantic bugs in the compiler.
As a result of this change, const is now respected when passing 2-dimensional arrays as arguments.
In addition, the following declaration now emits a warning:
const int X;
This is because future assignment is no longer possible if "X" is a two-dimensional array.
> Remove nested array symbols.

- compiler/lexer.cpp
- vm/md5/md5.cpp
note: 'sprintf' has been explicitly marked deprecated here __deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
SourceMod Scripting CI failed on mac due to this.
https://github.com/alliedmodders/sourcemod/actions/runs/3979033169/jobs/6821186383
> Remove usage of sprintf on newer apple-clang

- compiler/messages.h
- compiler/semantics.cpp
- tests/compile-only/fail-subexpr-in-comma-has-no-effect.sp
- tests/compile-only/fail-subexpr-in-comma-has-no-effect.txt
Bug: issue #877
Test: new test
> Add warning when comma expressions contain discarded non-effectful subexpressions.

- AMBuildScript
- compiler/array-helpers.cpp
- compiler/assembler.cpp
- compiler/compile-context.cpp
- compiler/compile-context.h
- compiler/errors.cpp
- compiler/errors.h
- compiler/expressions.cpp
- compiler/lexer.cpp
- compiler/lexer.h
- compiler/main.cpp
- compiler/name-resolution.cpp
- compiler/parser.cpp
- compiler/semantics.cpp
- compiler/source-file.cpp
- compiler/source-file.h
- compiler/source-location.h
- compiler/source-manager.cpp
- compiler/source-manager.h
- compiler/symbols.cpp
- compiler/symbols.h
- tests/runtests.py
This is a big refactoring of how tokens are tracked throughout the compiler.
Rather than carry explicit file and column information on every token, instead we now track a 32-bit encoded location id. This id can be decoded back to a specific file, column, and line. It's much more compact, and it supports correct tracking of macro expanded tokens (which can cross file boundaries). It can also track the complete #include lineage of a token.
Gradually, the error reporter and AST will migrate to the new location id. The lexer still needs token_pos_t, which tracks the decoded line number. Decoding line numbers from a location id is very expensive, and the hottest function in the lexer is peek_same_line() which relies on this information.
The motivation for this is twofold. First, it makes …
> Track tokens more accurately, and compactly.

- compiler/errors.cpp
- compiler/errors.h
- compiler/name-resolution.cpp
- compiler/semantics.cpp
- compiler/source-file.cpp
- compiler/source-file.h
- compiler/source-manager.cpp
- compiler/source-manager.h
- compiler/symbols.cpp
- compiler/symbols.h
This is easy now that we have proper location encoding.
The current formatting is debatable, but it's a start.
Example:
test.sp(3) : error 017: undefined symbol "ham"
3 |     int hello = ham;
-------------------------^
test.sp(4) : error 017: undefined symbol "hhello"
4 |     return hhello
--------------------^
> Add beautiful error messages.

- compiler/lexer.cpp
- compiler/lexer.h
- compiler/main.cpp
- compiler/messages.h
- compiler/parser.cpp
- compiler/parser.h
- compiler/semantics.cpp
- compiler/semantics.h
- tests/compile-only/file-reporting/fail-main.txt
In the early days of AMX Mod X/SourceMod there weren't really good
source editors. Many people used Notepad for their scripting. Mixing
tabs/spaces and getting indents wrong was very common.
These days there are a few factors that make this less critical:
- There are many high quality editors available, and there is much
more awareness around them.
- The industry has basically settled on spaces for indentation.
- Modern programming languages tend to come with auto-formatting tools now as
well, which is probably something SourcePawn should do.
Either way, the inline linter is a huge, huge hack and has no business
being right there in the lexer. It makes token caching very complex.
It's slow. And it requires knowing a predefined value for tabsizes,
which makes no sense.
So awaaaay it goes.
> Remove the indentation warning. 

- compiler/messages.h
- compiler/parser.cpp
- tests/compile-only/fail-method-requires-brace.txt
This is not a change I wanted to make, but I think it is necessary. Unfortunately it breaks over 250 legacy, pre-transitional syntax plugins in the corpus, that are going to be removed. That shrinks the corpus by 1.6%.
The reason is quite complex.
SourcePawn has an AST problem: the parsing AST is not distinct from the semantic AST, which means the semantics phase has no choice but to apply annotations to the AST to add type information. That is very inflexible, and I am not sure how to solve issue #844, because it requires rebuilding the AST recursively.
Compiler projects that have infinite resources (in every sense of the word) can just keep generating new ASTs. For example, Rosyln does this (it separates grammar AST from binding AST, etc). That's quite nice. However it's expensive, and …
> Require braces for global function bodies.

- compiler/lexer.cpp
- compiler/lexer.h
- compiler/parse-node.h
- compiler/parser.cpp
- compiler/parser.h
This patch skips parsing function bodies, instead caching tokens and attaching the token stream to the AST. After the AST is built, functions are parsed using cached tokens. This is fairly easy to do thanks to the recent Lexer/SourceManager refactoring.
This is a critical step toward collapsing the binding and semantic passes together, without re-introducing a dreaded reparse phase.
A quick estimate shows that memory use on this is pretty small. For funcommands.sp (the biggest plugin in the test suite), it's about 200KB. This is again thanks to the recent refactoring. Tokens are now 24 bytes instead of 96 bytes.
Duplicating the AST would use about 3MB since the AST is so unoptimized, and culling that down is a big project.
> Delay function body parsing.

- compiler/builtins.h
- compiler/driver.cpp
- compiler/errors.cpp
- compiler/lexer.cpp
- compiler/lexer.h
- compiler/main.cpp
- compiler/parser.cpp
- compiler/sc.h
This gets rid of DIRSEP_CHAR and a lot of manual string code.
It also fixes how file defines were created, which was mostly broken and working by accident.
Finally, it fixes a crash on the command-line if the input file was not found.
> Replace manual path mucking with std::filesystem.

- compiler/compile-context.h
- compiler/lexer.cpp
- compiler/parser.cpp
- compiler/parser.h
- compiler/source-file.h
- compiler/stl/stl-deque.h
If two #included files have the same inode, only the first include will be parsed. this obsoletes the "#if ... #endinput" hack in every include file.
Nominally #include in SourcePawn was the same as C/C++, where you can include the same file over and over. This is useful in C/C++ for creating macro expansion tables. It's not useful in Pawn, where those tricks don't work, and as evidenced by the fact that not a single plugin in the corpus was affected by this change.
This greatly simplifies how static scopes are handled, since SourcePawn's notion of a static scope is per-file, rather than per-translation unit. This simplification re-opens the door to multiple translation units, an important step for an upcoming refactoring of how builtins work.
> Do not include files that have already been included.

- README.md
- compiler/assembler.cpp
- compiler/expressions.cpp
- compiler/main.cpp
- compiler/messages.h
- compiler/types.cpp
- compiler/types.h
- include/smx/smx-headers.h
- include/sp_vm_api.h
- tests/api/function-id.sp
- vm/plugin-context.cpp
- vm/plugin-context.h
- vm/shell/shell.cpp
- vm/smx-v1-image.cpp
INVALID_FUNCTION was proving to be a major pain; setting it to -1 might be one of the dumbest things I've done. It had a few problems all boiling down to "there is no support in the compiler for non-zero false values". Eg, `f1 == f2` is false below:
Function f1;
Function f2 = INVALID_FUNCTION;
We could have gone through and fixed all the edge cases like this throughout the compiler, but it seems counter-productive.
The other oddity is that because `null` is 0, `INVALID_FUNCTION` needed a separate unit type, which we called `nullfunc_t`.
Rather than keep propping up all this weirdness, this patch normalizes `INVALID_FUNCTION` by making it equivalent to `null`. Its value is 0, and its type is `null_t`.
This will break compatibility with cross-plugin interactions, so plugins sharing a …
> Remove nullfunc_t and make INVALID_FUNCTION the same as null.

- compiler/lexer.cpp
- compiler/lexer.h
- compiler/parser.cpp
Make sure that a successful function parse actually terminates the injected token stream. Also, drop the injected token stream in case parsing failed.
> Clean up injected token state.

- compiler/assembler.cpp
- compiler/code-generator.cpp
- compiler/messages.h
- compiler/name-resolution.cpp
- compiler/parse-node.h
- compiler/parser.cpp
- compiler/symbols.cpp
- compiler/symbols.h
- include/core/float.inc
- tests/sourcemod/include/float.inc
This was an obscure feature used to make float.inc easier to write. It was also briefly used to make methmodmaps easier to write. However it's full of idiosyncracies and there is no type checking whatsoever for aliases.
This will require a tiny bit of fixup on the SourceMod side, but otherwise has no impact. The corpus will fail until SM is updated.
> Remove support for function aliases.

- compiler/semantics.cpp
- compiler/semantics.h
- tests/compile-only/fail-property-rvalue-no-getter.sp
- tests/compile-only/fail-property-rvalue-no-getter.txt
Long-term, most simple calls to CheckRvalue should return a new RvalueExpr, but our current AST has no sane way to be rebuilt bottom-up.
Bug: issue #844
> Convert most calls of CheckExpr to require a valid r-value.

- compiler/assembler.cpp
- compiler/code-generator.cpp
- compiler/expressions.h
- compiler/name-resolution.cpp
- compiler/parse-node.cpp
- compiler/parse-node.h
- compiler/parser.cpp
- compiler/semantics.cpp
- compiler/semantics.h
- compiler/types.cpp
- compiler/types.h
Pstructs had ancillary structures that were completely obviated by AST types. Remove these and refactor callers.
> Clean up pstruct implementation details.

- compiler/name-resolution.cpp
- compiler/semantics.cpp
- tests/compile-only/ok-argument-shadows-function.sp
- tests/compile-only/warn-unused-arg.sp
- tests/compile-only/warn-unused-arg.txt
These changes fix #784
`tests/compile-only/warn-unused-arg.sp` adds coverage for unused arguments in `public`, `static`, `stock` and regular functions
Note that `tests/compile-only/ok-argument-shadows-function.sp` had to be modified (`#pragma unused` added) to take into account that arguments should now be used in stock functions.
Feel free to tell me if I missed anything!
> Unused arguments in stock functions are now triggering warnings

- compiler/assembler.cpp
- compiler/code-generator.cpp
- compiler/expressions.cpp
- compiler/name-resolution.cpp
- compiler/parser.cpp
- compiler/semantics.cpp
- compiler/smx-assembly-buffer.h
- compiler/types.cpp
- compiler/types.h
- compiler/value-inl.h
Historically, Pawn constructed critical type information from two sources of information: the tag, and the identifier kind. The identifier kind describes whether the value refers to an array, variable, expression result, reference, etc.
IdentifierKind is hugely problematic since it's not formally part of the type. This means it can't participate in things like matchtag() and find_userop(). It also creates situations where the two can become out of sync. For example, changing iREFERENCE to iVARIABLE without an RvalueExpr is a bug that is no longer possible.
With the recent removal of "semantic tags", we were able to remove iENUMSTRUCT. Now, we are removing iREFERENCE, and creating a new reference type. As before, this requires some auditing and additional type checks. Mostly though, it is …
> Remove iREFERENCE and add a new reference type.

- compiler/assembler.cpp
- compiler/code-generator.cpp
- compiler/messages.h
- compiler/name-resolution.cpp
- compiler/semantics.cpp
- compiler/smx-assembly-buffer.h
- compiler/types.cpp
- compiler/types.h
- vm/opcodes.cpp
The only real difference between iARRAY and iREFARRAY is that local
iARRAYs are allocated on the stack, whereas iREFARRAY declarations are
allocated on the heap (with GENARRAY).
Long-term, all arrays should be allocated in the VM, not the compiler.
Let's bite the bullet now and remove this oddity. This will make it
simpler to unify how arrays work.
With this change, the stack exclusively contains scalars. All local
arrays are allocated on the heap, and their addresses are stored in a
stack variable.
Global and static arrays are unaffected since all global arrays are
iARRAYs.
> Eliminate stack arrays.

- compiler/array-helpers.cpp
- tests/compile-only/fail-array-default-argument-mismatch.sp
- tests/compile-only/fail-array-default-argument-mismatch.txt
This now fails:
int Array[2][3];
void f(int array[3][2] = Array) {}
> Fix bug where default array assignment wasn't fully checked.

- compiler/assembler.cpp
- compiler/code-generator.cpp
- compiler/parse-node.cpp
- compiler/parse-node.h
- compiler/types.h
- vm/rtti.cpp
Add a QualType wrapper around Type + const, and use this to significantly simplify RTTI.
> Simplify type building in RTTI.

- vm/environment.cpp
- vm/interpreter.cpp
- vm/jit.cpp
- vm/method-info.h
Split it into JIT and interpreter variants, since the interpreter never uses the graph.
Bug: issue #965
Test: manual benchmark
> Fix MethodVerifier::Validate not making any sense.

- compiler/array-helpers.cpp
- compiler/assembler.cpp
- compiler/expressions.cpp
- compiler/name-resolution.cpp
- compiler/parser.cpp
- compiler/semantics.cpp
- compiler/types.cpp
- compiler/types.h
- tests/compile-only/ok-reparse-newdecl-array.sp
This removes more cruft leftover from the tag system, and merges the dimension vector into typeinfo_t::dim_exprs. This is roughly a 4-5% reduction in memory usage, but the real goal is another step toward eliminating matchtag() and iFUNCTN.
> Remove typeinfo_t::dim_.

- compiler/assembler.cpp
- compiler/errors.cpp
- compiler/errors.h
- compiler/expressions.cpp
- compiler/expressions.h
- compiler/name-resolution.cpp
- compiler/parse-node.h
- compiler/sctracker.cpp
- compiler/sctracker.h
- compiler/type-checker.cpp
- compiler/type-checker.h
- compiler/types.cpp
- compiler/types.h
- include/smx/smx-typeinfo.h
- vm/rtti.cpp
This thing was pretty old. Using typeinfo_t is problematic because it's pre-binding. Move it to QualType, and create a formal FunctionType class.
This is a prerequisite to removing funcenum_t.
> Move functag_t into the type system.

- compiler/array-helpers.cpp
- tests/compile-only/fail-string-too-big-for-array.sp
- tests/compile-only/fail-string-too-big-for-array.txt
Bug: issue #971
Test: new test case, modified corpus
> Forbid initializing string arrays with literals that are too long.

- compiler/semantics.cpp
- compiler/type-checker.cpp
- tests/compile-only/ok-inner-enum-struct-to-any.sp
- tests/sourcemod/include/testing.inc
- tests/sourcemod/testsuite/mock/test_sorting.sp
Fixes passing inner structs to any[].
Fixes coercing any[] to int[].
Bug: issue #973
> Fix some type checking regressions.

- tests/testutil.py
This was replaced with read_file() in version 3.2. Added a try cactch block around this code so we can delegate through to either version.
Testing scripts runs correctly with python 3.12.4.
> Update use of Removed ConfigParser.readfp() Function

- compiler/semantics.cpp
- tests/compile-only/ok-static-used-by-stock.inc
- tests/compile-only/ok-static-used-by-stock.sp
This adds stock functions to the maybe used set which seems most appropriate.
We can then mark all of the functions they refer too as maybe used also.
Added a new compile only test which should fail if there are any warnings.
> Fix for #972 when a static is used by a stock Function

- .github/workflows/ci.yml
These appear to no longer work.
> Turn down arm32 builders.

- compiler/expressions.cpp
- tests/compile-only/fail-ref-compare-function-signature.sp
- tests/compile-only/fail-ref-compare-function-signature.txt
Bug: issue #992
Test: new test cases
> Fix bugs in function signature type checking.
